---
title: "Statistical Analysis of Thesis Data"
author: "CG Viljoen - VLJCHR004"
date: "06/05/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = F,warning = F)
```

```{r}
wrangle <- function(dirX){
  
  require(jsonlite)
  
  files <- list.files(path=paste0(dirX),
                      pattern="*json",
                      full.names=T,
                      recursive=TRUE)
  
  j <- fromJSON(files[1])
  
  #print("---------------------------------------------------------------------------------")
  #print(paste0("Processing jsons to list:"))
  
  L <- length(files)
  
  for(i in 2:L){
    #print(100*(i/L))
    
    f <- fromJSON(files[i])
    j <- c(j,f)
  }
  
  j
  
}

```

```{r}
#define a function to recursively add actual run numbers and concatenate lists
recursive_add <- function(run_number){
  run_number <- paste0("000",run_number)
  
  dirX <- paste0("C:/Users/gerhard/Documents/msc-thesis-data/processed/",run_number)
  dat_ <- wrangle(dirX)
  
  for(i in 1:length(dat_)){
  
  dat_[[i]]$RunNumber <- run_number
  }
  
  dat <- c(dat,dat_)
}

#add first run to initialize dataset

dirX = "C:/Users/gerhard/Documents/msc-thesis-data/processed/000265309"
dat <- wrangle(dirX)

for(i in 1:length(dat)){
  
  dat[[i]]$RunNumber <- "000265309"
  
}

runs <- c("000265332","000265334","000265335",
          "000265336","000265338","000265339",
          "000265342","000265343","000265344",
          "000265377","000265378","00026581",
          "00026583","00026585","000265388")

for(i in runs){
  recursive_add(i)
}
```


```{r}
names(dat[[1]])
```

```{r}
Eta <- sapply(dat, `[[`,"Eta")
P <- sapply(dat, `[[`,"P")
PT <- sapply(dat, `[[`,"PT")
Phi <- sapply(dat, `[[`,"Phi")
Theta <- sapply(dat, `[[`,"Theta")
dEdX <- sapply(dat, `[[`,"dEdX")
nSigmaElectron <- sapply(dat, `[[`,"nSigmaElectron")
nSigmaPion <- sapply(dat, `[[`,"nSigmaPion")
pdgCode <- sapply(dat, `[[`,"pdgCode")

dat <- data.frame(cbind(Eta,P,PT,
                              Phi,Theta,dEdX,
                              nSigmaElectron,nSigmaPion,
                              pdgCode))

dat$particleID <- ifelse(abs(dat$pdgCode)==211,"pion","electron")

dat$RunNumber <-  sapply(dat, `[[`,"RunNumber")
dat$RunNumber <- as.factor(dat$RunNumber)
```



```{r}
require(ggplot2)

ggplot(dat,aes(x=factor(particleID),colour=factor(particleID),fill="white"))+
  geom_bar()+
  ggtitle("Number of Electrons and Pions")+facet_wrap(~RunNumber)
```



```{r}
ggplot(dat,aes(x=P,y=PT,colour=factor(particleID),alpha=0.2))+geom_violin()+facet_wrap(~RunNumber)
```


```{r}
ggplot(dat,aes(x=P,y=dEdX,colour=factor(particleID),alpha=0.2))+geom_line()+facet_wrap(~RunNumber)
```

```{r}
ggplot(dat,aes(x=PT,y=dEdX,colour=factor(particleID),alpha=0.2))+geom_line()+facet_wrap(~RunNumber)
```


```{r}
ggplot(dat,aes(x=Theta,y=Eta,fill=factor(particleID),alpha=0.2))+geom_violin()+facet_wrap(~RunNumber)
```


```{r}
ggplot(dat[dat$nSigmaElectron!=-999,],aes(x=P[dat$nSigmaElectron!=-999],
                     y=nSigmaElectron[dat$nSigmaElectron!=-999],
                     colour=factor(particleID[dat$nSigmaElectron!=-999]),
                     alpha=0.1))+geom_line()+facet_wrap(~RunNumber)



```




```{r}
ggplot(dat[dat$nSigmaPion!=-999,],aes(x=P[dat$nSigmaPion!=-999],
                     y=nSigmaPion[dat$nSigmaPion!=-999],
                     colour=factor(particleID[dat$nSigmaPion!=-999]),
                     alpha=0.1))+geom_line()+facet_wrap(~RunNumber)
```

```{r}
ggplot(dat[dat$nSigmaElectron!=-999,],aes(x=dEdX[dat$nSigmaElectron!=-999],
                     y=nSigmaElectron[dat$nSigmaElectron!=-999],
                     colour=factor(particleID[dat$nSigmaElectron!=-999]),
                     alpha=0.1))+geom_line()+facet_wrap(~RunNumber)
```



```{r}
ggplot(dat[dat$nSigmaPion!=-999,],aes(x=dEdX[dat$nSigmaPion!=-999],
                     y=nSigmaPion[dat$nSigmaPion!=-999],
                     colour=factor(particleID[dat$nSigmaPion!=-999]),
                     alpha=0.1))+geom_line()+facet_wrap(~RunNumber)
```

















