---
title: "Statistical Analyses"
author: "Gerhard Viljoen"
date: "05/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())


load("C:/Users/Gerhard/Documents/msc-thesis-data/aux_.rdata")
load("C:/Users/Gerhard/Documents/msc-thesis-data/meta.rdata")
load("C:/Users/Gerhard/Documents/msc-thesis-data/x.rdata")
load("C:/Users/Gerhard/Documents/msc-thesis-data/y.rdata")

dim(x) <- c(dim(x)[1],17,24)

cs <- apply(x,1,colSums)


names(meta)
names(aux)

meta <- data.frame(meta,aux,y)

rm(aux,y)

names(meta)


fac_cols <- c(4,5,6,7,13)

for(i in fac_cols){
  meta[,i] <- as.factor(meta[,i])
}

non_fac_cols <- 1:ncol(meta)[-fac_cols]

for(i in non_fac_cols){
  meta[,i] <- as.numeric(meta[,i])
}

```

```{r}
t <- data.frame(table(meta$y))

names(t)[1] <- "Particle ID"

t$`Particle ID` <- c("pion","electron")

t$Percent <- c(round(t$Freq[1]/sum(t$Freq)*100,2),round(t$Freq[2]/sum(t$Freq)*100,2))

require(ggplot2)

ggplot(t,aes(x=`Particle ID`, y= `Freq`,fill=`Particle ID`))+geom_bar(stat = "identity")+geom_text(label=c(paste0(t$Freq[1],"\n (",t$Percent[1],"%)"),paste0(t$Freq[2],"\n (",t$Percent[2],"%)")))

```


```{r}

library("RColorBrewer")

meta$y <- ifelse(as.numeric(as.character(meta$y))==1,"electron","pion")

# table(meta$y)

meta$y <- ifelse(as.character(meta$y)=="electron","pion","electron")

myPalette <- colorRampPalette((brewer.pal(11, "Spectral")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(0, 100))

# table(meta$dEdX,meta$P)

# install.packages("hexbin")
# 
bethe_bloch = meta[(meta$y=="electron"&meta$P>=1.5)|(meta$y=="pion"&meta$P>=2),]

ggplot(bethe_bloch,aes(y=dEdX,x=P))+geom_hex(bins=1000)+facet_wrap(~y)+xlab("Momentum (GeV/c)")+ylab("dE/dX (Arbitrary Units)")+myPalette <- colorRampPalette((brewer.pal(11, "Spectral")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(0, 100))

# table(meta$dEdX,meta$P)

# install.packages("hexbin")
# 
# bethe_bloch = meta[(meta$y=="electron"&meta$P>=1.5)|(meta$y=="pion"&meta$P>=2),]

ggplot(bethe_bloch,aes(y=dEdX,x=P))+geom_hex(bins=1000)+facet_wrap(~y)+xlab("Momentum (GeV/c)")+ylab("dE/dX (Arbitrary Units)")+geom_line()

# ggplot(meta,aes(y=dEdX,x=PT))+geom_hex(bins=1000)+facet_wrap(~y)+xlab("Transverse Momentum (P_T) (GeV/c)")+ylab("dE/dX (Arbitrary Units)")
```


```{r}
dim(cs)

cs <- t(cs)

names(cs)

cs <- data.frame(cbind(cs,meta$y))

typeof(cs$meta.y)

cs$meta.y[1]

table(cs$meta.y)

cs$y <- ifelse(cs$meta.y==1,"pion","electron")

require(dplyr)

cs <- cs %>%
  group_by(y) %>%
  summarise(X1=mean(X1),X2=mean(X2),
            X3=mean(X3),X4=mean(X4),
            X5=mean(X5),X6=mean(X6),
            X7=mean(X7),X8=mean(X8),
            X9=mean(X9),X10=mean(X10),
            X11=mean(X11),X12=mean(X12),
            X13=mean(X13),X14=mean(X14),
            X15=mean(X15),X16=mean(X16),
            X17=mean(X17),X18=mean(X18),
            X19=mean(X19),X20=mean(X20),
            X21=mean(X21),X22=mean(X22),
            X23=mean(X23),X24=mean(X24))

cs <- t(cs)

cs <- data.frame(cs)

names(cs) <- cs[1,]

cs <- cs[-1,]

names(cs) <- c("electron","pion")

require(reshape2)

# cs <- cs %>%
#   reshape2::melt()

el_t <- cbind(as.numeric(as.character(cs$electron)),"electron")
pi_t <- cbind(as.numeric(as.character(cs$pion)),"pion")

cs2 <- data.frame(rbind(el_t,pi_t))

names(cs2) <- c("Pulse height","Particle ID")

cs2$`Pulse height` <- as.numeric(as.character(cs2$`Pulse height`))

require(ggplot2)

cs2$timebin <- 1:24

ggplot(cs2,aes(x=timebin,y=`Pulse height`,col=`Particle ID`))+geom_line()+ylab("Average Pulse Height (mv)")+xlab("Time bin (Arbitrary Units)")
```





































