---
title: "Final Slog"
author: "Gerhard Viljoen"
date: "26/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Real V Geant

```{r}
rm(list=ls())

load("c:/Users/gerhard/Documents/msc-thesis-data/hijing-sim/sim_x_full.rdata")
load("c:/Users/gerhard/Documents/msc-thesis-data/hijing-sim/real_x_full.rdata")
```

```{r}
require(abind)
x_train = abind(real_x,sim_x,along=1)

y_train = c(rep(1,dim(real_x)[1]),rep(0,dim(sim_x)[1]))

dim(x_train) = c(dim(x_train),1)

require(keras)
model <- keras_model_sequential() %>%
  layer_conv_2d(16, kernel_size = c(4,4),activation = "tanh") %>%
  layer_max_pooling_2d() %>%
  layer_conv_2d(32, kernel_size = c(4,4),activation = "tanh") %>%
  layer_max_pooling_2d() %>%
  layer_flatten() %>%
  layer_dense(512,"tanh") %>%
  layer_dense(256,"tanh") %>%
  layer_dense(128,"tanh") %>%
  layer_dense(1, "sigmoid")

model %>%
  compile(
    loss="binary_crossentropy",
    optimizer_adam(0.00001),
    metrics="acc"
    
  )
  
history <- model %>%
  fit(x_train,
      y_train,
      batch_size=32,
      verbose=2,
      epochs=30,
      shuffle=TRUE)

png("C:/Users/gerhard/documents/MSc-thesis/NEW/ML/geant_v_real_FINAL.png")
plot(history)
dev.off()
```

```{r}
preds <- data.frame(cbind(predict(model,x_train)),ifelse(y_train==1,"real","geant"))
```

```{r}
require(ggplot2)

names(preds) <- c("P(real)","Datatype")

preds$`P(real)` <- as.numeric(as.character(preds$`P(real)`))

preds$Datatype <- as.factor(preds$Datatype)

ggplot(preds,aes(x=preds$`P(real)`,fill=Datatype,colour=Datatype))+geom_histogram(stat="count")+
  xlab("P(real)")
```


```{r}
require(plot.matrix)
par(mar=c(0,0,1,5))
plot(x_train[which(preds$`P(real)`<=0.001&as.character(preds$Datatype)=="geant")[1],,,],col=gray.colors(start=0,n=10),
     main=paste0('Geant: P(real) = ',round(preds$`P(real)`[which(preds$`P(real)`<=0.001&as.character(preds$Datatype)=="geant")[1]],4)),
     xlab='',ylab='',cex=0.02,axis.col =NULL,axis.row=NULL,border=NA)

```


```{r}
require(plot.matrix)
par(mar=c(0,0,1,5))
plot(x_train[max(which(preds$`P(real)`>=0.9&preds$`P(real)`<=1.0&as.character(preds$Datatype)=="geant")),,,],col=gray.colors(start=0,n=10),
     main=paste0('Geant: P(real) = ',round(preds$`P(real)`[max(which(preds$`P(real)`>=0.9&preds$`P(real)`<=1.0&as.character(preds$Datatype)=="geant"))],4)),
     xlab='',ylab='',cex=0.02,axis.col =NULL,axis.row=NULL,border=NA)

```

```{r}
require(plot.matrix)
par(mar=c(0,0,1,5))
plot(x_train[max(which(preds$`P(real)`>=0.9999&preds$`P(real)`<=1.0&as.character(preds$Datatype)=="geant")),,,],col=gray.colors(start=0,n=10),
     main=paste0('Geant: P(real) = ',round(preds$`P(real)`[max(which(preds$`P(real)`>=0.9999&preds$`P(real)`<=1.0&as.character(preds$Datatype)=="geant"))],4)),
     xlab='',ylab='',cex=0.02,axis.col =NULL,axis.row=NULL,border=NA)

```

```{r}
save_model_hdf5(model,"C:/USers/gerhard/Documents/msc-thesis/geant_discrim_model.h5")

sim_preds <- preds[which(as.character(preds$Datatype)=="geant"),1]
save(sim_preds,file="C:/USers/gerhard/Documents/msc-thesis/geant_preds.rdata")
```

```{r}
rm(list=ls())

require(keras)

load("c:/Users/gerhard/Documents/msc-thesis-data/hijing-sim/real_x_full.rdata")

sim_x <- read.csv("C:/Users/Gerhard/Documents/msc-thesis-data/simulated_datasets/simulated_data_aae12/sim_flat.csv",
                  header=FALSE,sep=",",dec=".",nrows=1000000)

sim_x <- as.matrix(sim_x)


###what the fuccccck

tst <- sim_x[1:100,]

tst <- aperm(tst,dim=c(100,17,24),perm = c(2,1))

real_x <- real_x[1:1000000,,]

dim(real_x) <- c(1000000,17,24,1)

require(scales)

sim_x = rescale(sim_x,to=c(min(real_x),max(real_x)))
```

```{r}
require(plot.matrix)
for(i in 1:50){
t <- tst[i,,]
t <- as.matrix(t)
plot(t)  
}

```






























