---
title: "Ensemble"
author: "Gerhard Viljoen"
date: "26/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
rm(list=ls())
load("c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```



```{r}
rm(meta)

signal <- singal

rm(singal)
```


```{r}
y <- ys[,1]
```


```{r}
names(signal)

signal <- signal[,1:41]

rm(ys)
```

```{r}
# if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
# if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }
# 
# # Next, we download, install and initialize the H2O package for R.
# install.packages("h2o", repos=(c("http://s3.amazonaws.com/h2o-release/h2o/master/1497/R", getOption("repos"))))


```



```{r}
require(h2o)



localH2O = h2o.init()
```


```{r}
signal <- scale(signal)

y <- ifelse(y==1,"electron","pion")

y <- as.factor(y)
```

```{r}
dat.hex <- as.h2o(data.frame(cbind(signal,y)))

dat.hex$y <- as.factor(dat.hex$y)
```

```{r}
splitz <- h2o.splitFrame(dat.hex,0.75,c("train.hex","test.hex"))

train.hex <- splitz[[1]]
test.hex <- splitz[[2]]
```



```{r}
rm(signal,dat.hex,splitz,y)
```


```{r,eval=F}
train.hex$y <- as.factor(train.hex$y)

rf <- h2o.randomForest(x=1:41,y=42,training_frame = train.hex,model_id = "rf1",nfolds = 10,verbose = TRUE)

h2o.confusionMatrix(rf,test.hex)
```

```{r}

model_path = "C:\\Users\\Gerhard\\Documents\\MSc-thesis\\NEW\\ML\\rf1"
rf <- h2o.loadModel(model_path)

h2o.performance(rf,newdata = test.hex)

h2o.confusionMatrix(rf,newdata=test.hex)




```


```{r}
rf_preds <- h2o.predict(rf,test.hex)

rf_preds <- as.data.frame(rf_preds)

preds <- rf_preds$p1

act <- as.data.frame(test.hex$y)

pred_act <- cbind(preds,act)

pred_act$y <- ifelse(pred_act$y==1,1,0)

```


```{r}
pred_act <- data.frame(pred_act)

names(pred_act) <- c("pred","act")

pi <- which(pred_act$act==1)
el <- which(pred_act$act!=1)

while(length(pi)%%6!=0){
  #print(length(pi))
  pi <- pi[-length(pi)]
  
}

while(length(el)%%6!=0){
  #print(length(el))
  el <- el[-length(el)]
  
}

pred_act <- pred_act[c(el,pi),]

six_tracklet_pred <- c()

for(i in seq(1,nrow(pred_act),6)){
  j=i+5
  
  this.dat <- prod(pred_act$pred[i:j])/sum(prod(pred_act$pred[i:j]),prod(1-pred_act$pred[i:j]))
  
  six_tracklet_pred <- c(six_tracklet_pred,this.dat)
}

six_tracklet_pred <- data.frame(six_tracklet_pred)

six_tracklet_pred <- na.omit(six_tracklet_pred)

six_tracklet_real <- c()

for(i in seq(1,nrow(pred_act),6)){
  this.dat <- pred_act$act[i]
  six_tracklet_real <- c(six_tracklet_real,this.dat)
  
}

six_tracklet_real <- data.frame(six_tracklet_real)

which(is.na(six_tracklet_real))

pred_act <- data.frame(cbind(six_tracklet_pred,six_tracklet_real))

elec_pi_eff_func <- function(model_1.preds,model_1.labels){
  
    # model_1.preds <- read.csv(model_1.preds,header=F, sep="")
    # 
    # model_1.labels <- read.csv(model_1.labels,header=F, sep="")
    
    model_1 <- data.frame(cbind(model_1.preds,model_1.labels))
    
    model_1.electrons <- which(model_1[,2]==1)
    
    electrons <- model_1[model_1.electrons,]
    
    pions <- model_1[-as.numeric(model_1.electrons),]
    
    electrons <- data.frame(electrons)
    
    names(electrons) <- c("prediction","label")
    
    pions <- data.frame(pions)
    
    names(pions) <- c("prediction","label")
    
    electron_efficiency <- function(electrons.,par){
  
    electrons <- electrons.
    
    electrons$electron_pred <- ifelse(electrons$prediction>=par[1],1,0)
    
    correct <- ifelse(electrons$electron_pred==electrons$label,1,0)
    
    error_metric <- sum(correct)/nrow(electrons)
    
    error_metric <- (error_metric-0.9)^2
    
    return(error_metric)
  
}

  res <- optim(par=c(0),fn=electron_efficiency,lower = 0,upper = 1,electrons.=electrons,method="Brent")
  
  require(ggplot2)
  
  g <- ggplot(pred_act,aes(pred_act[,1],colour=factor(pred_act[,2])))+geom_histogram(bins = 1000)+facet_wrap(factor(pred_act[,2]))
  print(g)
  
  hist(pred_act[,1],breaks=1000)
  abline(v=res$par,col="red")
  
  electrons$predicted_label <- ifelse(electrons$prediction>=res$par,1,0)
  
  print(paste0("Electron Efficiency: ",sum(electrons$predicted_label)/nrow(electrons)))
  
  pions$predicted_label <- ifelse(pions$prediction>=res$par,1,0)
  
  pions$misclassified_as_electron <- ifelse(pions$predicted_label==1,1,0)
  
  print(paste0("Pion Efficiency: ",(sum(pions$misclassified_as_electron)/nrow(pions))))
  
  pred_act$final_pred <- ifelse(pred_act[,1]>=res$par,1,0)
  
  require(caret)
  
  print(caret::confusionMatrix(data=factor(pred_act$final_pred),reference = factor(pred_act[,2])))
  print("--------------------------------------------------------------------------------------------------")
  
}

elec_pi_eff_func(pred_act[,1],pred_act[,2])
```

```{r}
gb <- h2o.gbm(x=1:41,y=42,training_frame = train.hex,model_id = "gb1",nfolds = 10,verbose = TRUE)
```


























