---
title: "Go Wild"
author: "Gerhard Viljoen"
date: "21/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = F,warning = F)
```

```{r}
rm(list=ls())
```


```{r,eval=F}
require(jsonlite)
require(readtext)

#PDG codes
# pdg.elec <- c(11,-11)
# pdg.pion <- c(-211,211)

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265309", pattern="*json", full.names=T, recursive=T)

j <- fromJSON(files[1])

for(i in 2:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265332", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265334", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265335", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265336", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265338", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265339", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265342", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265343", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265344", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265377", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265378", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265381", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265383", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265385", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265388", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265419", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265420", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265425", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265426", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265499", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  j <- c(j,f)
}

```



```{r,eval=F}

Eta <- sapply(j, `[[`,"Eta")

P <- sapply(j, `[[`,"P")

PT <- sapply(j, `[[`,"PT")

Phi <- sapply(j, `[[`,"Phi")

Theta <- sapply(j, `[[`,"Theta")

col0 <- sapply(j, `[[`,"col0")

col1 <- sapply(j, `[[`,"col1")

col2 <- sapply(j, `[[`,"col2")

col3 <- sapply(j, `[[`,"col3")

col4 <- sapply(j, `[[`,"col4")

col5 <- sapply(j, `[[`,"col5")

dEdX <-  sapply(j, `[[`,"dEdX")

det0 <- sapply(j, `[[`,"det0")

det1 <- sapply(j, `[[`,"det1")

det2 <- sapply(j, `[[`,"det2")

det3 <- sapply(j, `[[`,"det3")

det4 <- sapply(j, `[[`,"det4")

det5 <- sapply(j, `[[`,"det5")

nSigmaElectron <- sapply(j, `[[`,"nSigmaElectron")

nSigmaPion <- sapply(j, `[[`,"nSigmaPion")

pdgCode <- sapply(j, `[[`,"pdgCode")

row0 <- sapply(j, `[[`,"row0")

row1 <- sapply(j, `[[`,"row1")

row2 <- sapply(j, `[[`,"row2")

row3 <- sapply(j, `[[`,"row3")

row4 <- sapply(j, `[[`,"row4")

row5 <- sapply(j, `[[`,"row5")

layer0 <- sapply(j, `[[`,"layer 0")

layer1 <- sapply(j, `[[`,"layer 1")

layer2 <- sapply(j, `[[`,"layer 2")

layer3 <- sapply(j, `[[`,"layer 3")

layer4 <- sapply(j, `[[`,"layer 4")

layer5 <- sapply(j, `[[`,"layer 5")

```


```{r,eval=F}
save.image(file="c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```

```{r,eval=F}
load("c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```


```{r,eval=F}
meta <- data.frame(cbind(col0,col1,col2,col3,col4,col5,det0,det1,det2,det3,det4,det5,
                         row0,row1,row2,row3,row4,row5,dEdX,Eta,nSigmaElectron,
                         nSigmaPion,P,pdgCode,PT,Theta,Phi))

save(meta,file="c:/Users/gerhard/documents/msc-thesis-data/meta.rdata")

rm(col0,col1,col2,col3,col4,col5,det0,det1,det2,det3,det4,det5,
                         row0,row1,row2,row3,row4,row5,dEdX,Eta,nSigmaElectron,
                         nSigmaPion,P,pdgCode,PT,Theta,Phi,f,j)

rm(files,i,pdg.elec,pdg.pion)
```


```{r,eval=F}
n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
```


```{r,eval=F}  
save.image(file="c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```


```{r,eval=F}
load("c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```


```{r,eval=F}
meta1 <- meta
meta2 <- meta
meta3 <- meta
meta4 <- meta
meta5 <- meta

rm(meta)

meta0 <- meta1
```


```{r,eval=F}
meta0 <- meta0[-n0,]
layer0 <- layer0[-n0]

meta1 <- meta1[-n1,]
layer1 <- layer1[-n1]

meta2 <- meta2[-n2,]
layer2 <- layer2[-n2]

meta3 <- meta3[-n3,]
layer3 <- layer3[-n3]

meta4 <- meta4[-n4,]
layer4 <- layer4[-n4]

meta5 <- meta5[-n5,]
layer5 <- layer5[-n5]

rm(n0,n1,n2,n3,n4,n5)


```


```{r,eval=F}  
save.image(file="c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```


```{r,eval=F}
load("c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```


```{r,eval=F}
meta0$layer <- 0
meta1$layer <- 1
meta2$layer <- 2
meta3$layer <- 3
meta4$layer <- 4
meta5$layer <- 5

meta0$col <- meta0$col0
meta0$det <- meta0$det0
meta0$row <- meta0$row0

meta1$col <- meta1$col1
meta1$det <- meta1$det1
meta1$row <- meta1$row1

meta2$col <- meta2$col2
meta2$det <- meta2$det2
meta2$row <- meta2$row2

meta3$col <- meta3$col3
meta3$det <- meta3$det3
meta3$row <- meta3$row3

meta4$col <- meta4$col4
meta4$det <- meta4$det4
meta4$row <- meta4$row4

meta5$col <- meta5$col5
meta5$det <- meta5$det5
meta5$row <- meta5$row5


```



```{r,eval=F}
meta0 <- meta0[,-c(1:18)]
meta1 <- meta1[,-c(1:18)]
meta2 <- meta2[,-c(1:18)]
meta3 <- meta3[,-c(1:18)]
meta4 <- meta4[,-c(1:18)]
meta5 <- meta5[,-c(1:18)]
```



```{r,eval=F}  
save.image(file="c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```


```{r,eval=F}
load("c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```

```{r,eval=F}
require(dummies)

meta0 <- as.data.frame(lapply(meta0,unlist))
meta1 <- as.data.frame(lapply(meta1,unlist))
meta2 <- as.data.frame(lapply(meta2,unlist))
meta3 <- as.data.frame(lapply(meta3,unlist))
meta4 <- as.data.frame(lapply(meta4,unlist))
meta5 <- as.data.frame(lapply(meta5,unlist))

meta <- data.frame(rbind(meta0,meta1,meta2,meta3,meta4,meta5))

meta <- dummy.data.frame(data=meta,names=list("layer","col","det","row"))
# 
# names(meta0)==names(meta1)
```




```{r,eval=F}
rm(meta0,meta1,meta2,meta3,meta4,meta5)
```


```{r,eval=F}
layer0 <- lapply(layer0, colSums)

layer0 <- do.call(rbind,layer0)

layer1 <- lapply(layer1, colSums)

layer1 <- do.call(rbind,layer1)

layer2 <- lapply(layer2, colSums)

layer2 <- do.call(rbind,layer2)

layer3 <- lapply(layer3, colSums)

layer3 <- do.call(rbind,layer3)

layer4 <- lapply(layer4, colSums)

layer4 <- do.call(rbind,layer4)

layer5 <- lapply(layer5, colSums)

layer5 <- do.call(rbind,layer5)



```



```{r,eval=F}
layers <- data.frame(rbind(layer0,
                           layer1,
                           layer2,
                           layer3,
                           layer4,
                           layer5))

layers <- as.data.frame(lapply(layers,unlist))

rm(layer0,layer1,layer2,layer3,layer4,layer5)
```



```{r,eval=F}  
save.image(file="c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
```



```{r}
# rm(list=ls())
# 
# require(jsonlite)
# require(readtext)
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265309", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 2:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c((lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c((lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c((lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c((lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# rm <- rbind((lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind((lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# runNumber <- rep(000265309,length(l0sd))
# 
# #
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265332", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265332,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265334", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265334,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265335", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265335,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265336", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# 
# runNumber <- c(runNumber,rep(000265336,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265338", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265332,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265339", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265339,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265342", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265342,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265343", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265343,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265344", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265344,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265377", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# 
# runNumber <- c(runNumber,rep(000265377,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265378", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265378,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265381", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265381,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265383", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265383,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265385", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265385,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265388", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265388,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265419", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265419,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265420", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# 
# runNumber <- c(runNumber,rep(000265420,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265425", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265425,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265426", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# runNumber <- c(runNumber,rep(000265426,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# 
# 
# files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265499", pattern="*json", full.names=T, recursive=T)
# 
# j <- fromJSON(files[1])
# 
# for(i in 1:length(files)){
# 
#   f <- fromJSON(files[i])
#   j <- c(j,f)
# }
# 
# layer0 <- sapply(j, `[[`,"layer 0")
# 
# layer1 <- sapply(j, `[[`,"layer 1")
# 
# layer2 <- sapply(j, `[[`,"layer 2")
# 
# layer3 <- sapply(j, `[[`,"layer 3")
# 
# layer4 <- sapply(j, `[[`,"layer 4")
# 
# layer5 <- sapply(j, `[[`,"layer 5")
# 
# n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
# n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
# n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
# n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
# n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
# n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
# 
# layer0 <- layer0[-n0]
# layer1 <- layer0[-n1]
# layer2 <- layer0[-n2]
# layer3 <- layer0[-n3]
# layer4 <- layer0[-n4]
# layer5 <- layer0[-n5]
# 
# l0sum <- c(l0sum,(lapply(layer0, sum)),
#            (lapply(layer1, sum)),
#            (lapply(layer2, sum)),
#            (lapply(layer3, sum)),
#            (lapply(layer4, sum)),
#            (lapply(layer5, sum)))
# 
# 
# l0max <- c(l0max,(lapply(layer0, max)),
#            (lapply(layer1, max)),
#            (lapply(layer2, max)),
#            (lapply(layer3, max)),
#            (lapply(layer4, max)),
#            (lapply(layer5, max)))
# 
# 
# l0mean <- c(l0mean,(lapply(layer0, mean)),
#             (lapply(layer1, mean)),
#             (lapply(layer2, mean)),
#             (lapply(layer3, mean)),
#             (lapply(layer4, mean)),
#             (lapply(layer5, mean))
#             )
# 
# 
# 
# l0sd <- c(l0sd,(lapply(layer0, sd)),
#           (lapply(layer1, sd)),
#           (lapply(layer2, sd)),
#           (lapply(layer3, sd)),
#           (lapply(layer4, sd)),
#           (lapply(layer5, sd)))
# 
# 
# runNumber <- c(runNumber,rep(000265499,length(layer0)+length(layer1)+
#                                length(layer2)+length(layer3)+
#                                length(layer4)+length(layer5)))
# 
# rm <- rbind(rm,(lapply(layer0, rowMeans)),
#           (lapply(layer1, rowMeans)),
#           (lapply(layer2, rowMeans)),
#           (lapply(layer3, rowMeans)),
#           (lapply(layer4, rowMeans)),
#           (lapply(layer5, rowMeans)))
# 
# cm <- rbind(cm,(lapply(layer0, colMeans)),
#           (lapply(layer1, colMeans)),
#           (lapply(layer2, colMeans)),
#           (lapply(layer3, colMeans)),
#           (lapply(layer4, colMeans)),
#           (lapply(layer5, colMeans)))
# 
# rm(f,j,layer0,layer1,layer2,layer3,layer4,layer5)
# 
# cm <- matrix(cm,ncol=24,byrow = T)
# rm <- matrix(rm,ncol=17,byrow = T)
# 
# add_info <- data.frame(cbind(l0max,l0mean,l0sd,l0sum,runNumber))
# 
# save(add_info,file="c:/Users/gerhard/documents/msc-thesis-data/add_info.rdata")
# 
# rm(cm,rm,files,i,l0max,l0mean,l0sd,l0sum,n0,n1,n2,n3,n4,n5,runNumber)
```

```{r,eval=F}
rm(meta)
rm(add_info)
```



```{r}
load("c:/Users/gerhard/documents/msc-thesis-data/all_data.rdata")
# 
# n <- which(is.na(layers))
# n <- which(is.null(layers))

#rm(n)
```


```{r}
names(layers)

add_info <- meta[,c(3,4)]
meta <- meta[,-c(3,4)]

y <- ifelse(abs(as.numeric(as.character(meta[,4]))==211),0,1)

meta <- meta[,-4]

x <- data.frame(cbind(meta,layers))

```





























