---
title: "Pad callibration"
author: "Gerhard Viljoen"
date: "28/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls())

require(jsonlite)
require(readtext)

#PDG codes
# pdg.elec <- c(11,-11)
# pdg.pion <- c(-211,211)

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265309", pattern="*json", full.names=T, recursive=T)

j <- fromJSON(files[1])

for(i in 2:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265309"
# }
  j <- c(j,f)
}



files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265332", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265332"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265334", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265334"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265335", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265335"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265336", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  
#   if(length(f)!=0){
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265336"
# }    
#   }
  

  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265338", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265338"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265339", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265339"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265342", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265342"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265343", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265343"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265344", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265344"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265377", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265377"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265378", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265378"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265381", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265381"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265383", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265383"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265385", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265385"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265388", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265388"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265419", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265419"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265420", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265420"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265425", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265425"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265426", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265426"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265499", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265499"
  # }
  # }
  j <- c(j,f)
}

```



```{r,eval=F}

Eta <- sapply(j, `[[`,"Eta")

P <- sapply(j, `[[`,"P")

PT <- sapply(j, `[[`,"PT")

Phi <- sapply(j, `[[`,"Phi")

Theta <- sapply(j, `[[`,"Theta")

col0 <- sapply(j, `[[`,"col0")

col1 <- sapply(j, `[[`,"col1")

col2 <- sapply(j, `[[`,"col2")

col3 <- sapply(j, `[[`,"col3")

col4 <- sapply(j, `[[`,"col4")

col5 <- sapply(j, `[[`,"col5")

dEdX <-  sapply(j, `[[`,"dEdX")

det0 <- sapply(j, `[[`,"det0")

det1 <- sapply(j, `[[`,"det1")

det2 <- sapply(j, `[[`,"det2")

det3 <- sapply(j, `[[`,"det3")

det4 <- sapply(j, `[[`,"det4")

det5 <- sapply(j, `[[`,"det5")

nSigmaElectron <- sapply(j, `[[`,"nSigmaElectron")

nSigmaPion <- sapply(j, `[[`,"nSigmaPion")

pdgCode <- sapply(j, `[[`,"pdgCode")

row0 <- sapply(j, `[[`,"row0")

row1 <- sapply(j, `[[`,"row1")

row2 <- sapply(j, `[[`,"row2")

row3 <- sapply(j, `[[`,"row3")

row4 <- sapply(j, `[[`,"row4")

row5 <- sapply(j, `[[`,"row5")

layer0 <- sapply(j, `[[`,"layer 0")

layer1 <- sapply(j, `[[`,"layer 1")

layer2 <- sapply(j, `[[`,"layer 2")

layer3 <- sapply(j, `[[`,"layer 3")

layer4 <- sapply(j, `[[`,"layer 4")

layer5 <- sapply(j, `[[`,"layer 5")

runNumber <- sapply(j, `[[`,"runNumber")

```

```{r}
meta <- data.frame(cbind(col0,col1,col2,col3,col4,col5,det0,det1,det2,det3,det4,det5,
                         row0,row1,row2,row3,row4,row5,dEdX,Eta,nSigmaElectron,
                         nSigmaPion,P,pdgCode,PT,Theta,Phi,runNumber))

rm(col0,col1,col2,col3,col4,col5,det0,det1,det2,det3,det4,det5,
                         row0,row1,row2,row3,row4,row5,dEdX,Eta,nSigmaElectron,
                         nSigmaPion,P,pdgCode,PT,Theta,Phi,runNumber)

rm(f,j,files,i)
```


```{r}
n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
```

```{r}
meta0 <- meta
meta1 <- meta
meta2 <- meta
meta3 <- meta
meta4 <- meta
meta5 <- meta

rm(meta)

meta0 <- meta0[-n0,]
layer0 <- layer0[-n0]

meta1 <- meta1[-n1,]
layer1 <- layer1[-n1]

meta2 <- meta2[-n2,]
layer2 <- layer2[-n2]

meta3 <- meta3[-n3,]
layer3 <- layer3[-n3]

meta4 <- meta4[-n4,]
layer4 <- layer4[-n4]

meta5 <- meta5[-n5,]
layer5 <- layer5[-n5]

rm(n0,n1,n2,n3,n4,n5)


```



```{r}
meta0$layer <- 0
meta1$layer <- 1
meta2$layer <- 2
meta3$layer <- 3
meta4$layer <- 4
meta5$layer <- 5

meta0$col <- meta0$col0
meta0$det <- meta0$det0
meta0$row <- meta0$row0

meta1$col <- meta1$col1
meta1$det <- meta1$det1
meta1$row <- meta1$row1

meta2$col <- meta2$col2
meta2$det <- meta2$det2
meta2$row <- meta2$row2

meta3$col <- meta3$col3
meta3$det <- meta3$det3
meta3$row <- meta3$row3

meta4$col <- meta4$col4
meta4$det <- meta4$det4
meta4$row <- meta4$row4

meta5$col <- meta5$col5
meta5$det <- meta5$det5
meta5$row <- meta5$row5
```

```{r}
meta0 <- meta0[,-c(1:18)]
meta1 <- meta1[,-c(1:18)]
meta2 <- meta2[,-c(1:18)]
meta3 <- meta3[,-c(1:18)]
meta4 <- meta4[,-c(1:18)]
meta5 <- meta5[,-c(1:18)]
```


```{r}
# meta0 <- as.data.frame(lapply(meta0,unlist))
# meta1 <- as.data.frame(lapply(meta1,unlist))
# meta2 <- as.data.frame(lapply(meta2,unlist))
# meta3 <- as.data.frame(lapply(meta3,unlist))
# meta4 <- as.data.frame(lapply(meta4,unlist))
# meta5 <- as.data.frame(lapply(meta5,unlist))

meta <- data.frame(rbind(meta0,meta1,meta2,meta3,meta4,meta5))
```


```{r}
barplot(c(length(layer0),length(layer1),length(layer2),length(layer3),length(layer4),length(layer5)),
        names.arg=c("layer0","layer1","layer2","layer3","layer4","layer5"),main = "Number of entries per layer number",
        sub="Outer layers are less frequently reached than inner layers",col="cornflowerblue")
```

```{r}
require(abind)

fix_dims <- function(x){
  dim(x) <- c(1,dim(x))#maybe need another 1 at the end?
}

test <- do.call(fix_dims,list(layer0[[1]],layer0[[2]]))

layer0 <- do.call(fix_dims,layer0)
layer1 <- do.call(fix_dims,layer1)
layer2 <- do.call(fix_dims,layer2)
layer3 <- do.call(fix_dims,layer3)
layer4 <- do.call(fix_dims,layer4)
layer5 <- do.call(fix_dims,layer5)

layer0 <- do.call(abind,layer0,along=1)
layer1 <- do.call(abind,layer1,along=1)
layer2 <- do.call(abind,layer2,along=1)
layer3 <- do.call(abind,layer3,along=1)
layer4 <- do.call(abind,layer4,along=1)
layer5 <- do.call(abind,layer5,along=1)

x <- abind(layer0,layer1,layer2,layer3,layer4,layer5,along=1)

rm(layer0,layer1,layer2,layer3,layer4,layer5)
```


```{r}
# barplot(c(mean(layer0),mean(layer1),mean(layer2),mean(layer3),mean(layer4),mean(layer5)),
#         names.arg=c("layer0","layer1","layer2","layer3","layer4","layer5"),main = "Mean ADC values per layer",
#         col="cornflowerblue")
```

```{r}
rm(meta0,meta1,meta2,meta3,meta4,meta5)
```

```{r}
require(dplyr)

taboo <- meta[,c("dEdX","nSigmaElectron","nSigmaPion","P","PT")]

names(meta)

meta <- meta[,-c(1,3,4,5,7)]

names(meta)

#Run Number did not populate for some reason

meta <- meta %>%
  select(-"runNumber")

y <- ifelse(abs(as.numeric(meta$pdgCode))==11,1,0)

```

```{r}

meta$Eta <- scale(as.numeric(meta$Eta))
meta <- meta[,-2]
meta$Theta <- scale(as.numeric(meta$Theta))
meta$Phi <- scale(as.numeric(meta$Phi))

meta$layer <- as.factor(meta$layer)



meta$col <- as.factor(unlist(meta$col))
meta$det <- as.factor(unlist(meta$det))
meta$row <- as.factor(unlist(meta$row))
```


```{r}
require(dummies)

meta <- dummy.data.frame(meta,names = c("layer","col","det","row"))

```



```{r}
save(meta,file = "C:/Users/gerhard/documents/msc-thesis-data/meta.rdata")
save(taboo,file = "C:/Users/gerhard/documents/msc-thesis-data/taboo.rdata")
save(x,file = "C:/Users/gerhard/documents/msc-thesis-data/x.rdata")
save(y,file = "C:/Users/gerhard/documents/msc-thesis-data/y.rdata")
```


```{r}
test_ind <- sample(1:nrow(meta),size=round(0.15*nrow(meta)),replace=F)

x_train <- x[-test_ind,,,]
x_test <- x[test_ind,,,]
meta_train <- meta[-test_ind,]
meta_test <- meta[test_ind,]
y_train <- y[-test_ind]
y_test <- y[test_ind]


```



# Autoencoder dim reduction

## Dim reduction on meta-data




```{r}
meta <- as.matrix(meta)

model <- keras_model_sequential()
model %>%
  layer_dense(units = 6, activation = "tanh", input_shape = ncol(meta_train)) %>%
  layer_dense(units = 2, activation = "tanh", name = "bottleneck") %>%
  layer_dense(units = 6, activation = "tanh") %>%
  layer_dense(units = ncol(meta_train))

summary(model)

model %>% compile(
  loss = "mean_squared_error", 
  optimizer = "adam"
)

# fit model
model %>% fit(
  x = meta_train, 
  y = meta_train, 
  epochs = 2000,
  verbose = 2
)

# evaluate the performance of the model
mse.ae2 <- evaluate(model, meta_train, meta_train)
mse.ae2

##        loss 
## 0.009725631

# extract the bottleneck layer
intermediate_layer_model <- keras_model(inputs = model$input, outputs = get_layer(model, "bottleneck")$output)
intermediate_output <- predict(intermediate_layer_model, meta_train)

ggplot(data.frame(PC1 = intermediate_output[,1], PC2 = intermediate_output[,2]), aes(x = PC1, y = PC2, col = factor(y_train))) + geom_point()

```


## Dim reduction on x data




```{r}
dim(x_train) <- c(dim(x_train)[1],dim(X_train)[2]*dim(x_train)[3])

x_train <- as.matrix(x_train)

model <- keras_model_sequential()
model %>%
  layer_dense(units = 36, activation = "tanh", input_shape = ncol(x_train)) %>%
  layer_dense(units = 12, activation = "tanh", name = "bottleneck") %>%
  layer_dense(units = 36, activation = "tanh") %>%
  layer_dense(units = ncol(x_train))

summary(model)

model %>% compile(
  loss = "mean_squared_error", 
  optimizer = "adam"
)

# fit model
model %>% fit(
  x = x_train, 
  y = x_train, 
  epochs = 2000,
  verbose = 2
)

# evaluate the performance of the model
mse.ae2 <- evaluate(model, x_train, x_train)
mse.ae2

##        loss 
## 0.009725631

# extract the bottleneck layer
intermediate_layer_model <- keras_model(inputs = model$input, outputs = get_layer(model, "bottleneck")$output)
intermediate_output <- predict(intermediate_layer_model, x_train)

ggplot(data.frame(PC1 = intermediate_output[,1], PC2 = intermediate_output[,2]), aes(x = PC1, y = PC2, col = factor(y_train))) + geom_point()

```








# Custom loss function

```{python,eval=F}
def focal_loss(gamma=2., alpha=.25):
	def focal_loss_fixed(y_true, y_pred):
		pt_1 = tf.where(tf.equal(y_true, 1), y_pred, tf.ones_like(y_pred))
		pt_0 = tf.where(tf.equal(y_true, 0), y_pred, tf.zeros_like(y_pred))
		return -K.mean(alpha * K.pow(1. - pt_1, gamma) * K.log(pt_1)) - K.mean((1 - alpha) * K.pow(pt_0, gamma) * K.log(1. - pt_0))
	return focal_loss_fixed

```

```{r}
require(keras)

require(tensorflow)

# Custom Focal Loss

fokLos <- function(y_true,y_pred,gamma=2.,alpha=.25){
  K <- keras::backend()
  pt_1 <- tf$where(tf$equal(y_true,1),y_pred,tf$ones_like(y_pred))
  pt_2 <- tf$where(tf$equal(y_true,0),y_pred,tf$ones_like(y_pred))
  return(-K$mean(alpha*K$pow(1.-pt_1,gamma)*K$log(pt_1))-K$mean((1-alpha)*K$pow(pt_0,gamma)*K$log(1.-pt_0)))
}

```
















