---
title: "real_vs_sim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
rm(list=ls())

require(jsonlite)

j <- fromJSON("C:/Users/gerhard/Documents/msc-thesis-data/hijing-sim/1.json")

##

layer0 <- sapply(j, `[[`,"layer 0")

pdgCode0 <- sapply(j, `[[`,"pdgCode")
n <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))

length(n)

layer0 <- layer0[-n]
pdgCode0 <- pdgCode0[-n]

for(i in 1:length(layer0)){
  layer0[[i]][which(layer0[[i]]==-7169)] <- 0
}

##

layer1 <- sapply(j, `[[`,"layer 1")

pdgCode1 <- sapply(j, `[[`,"pdgCode")
n <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))

length(n)

layer1 <- layer1[-n]
pdgCode1 <- pdgCode1[-n]

for(i in 1:length(layer1)){
  layer1[[i]][which(layer1[[i]]==-7169)] <- 0
}

##

layer2 <- sapply(j, `[[`,"layer 2")

pdgCode2 <- sapply(j, `[[`,"pdgCode")
n <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))

length(n)

layer2 <- layer2[-n]
pdgCode2 <- pdgCode2[-n]

for(i in 1:length(layer2)){
  layer2[[i]][which(layer2[[i]]==-7169)] <- 0
}

##

layer3 <- sapply(j, `[[`,"layer 3")

pdgCode3 <- sapply(j, `[[`,"pdgCode")
n <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))

length(n)

layer3 <- layer3[-n]
pdgCode3 <- pdgCode0[-3]

for(i in 1:length(layer3)){
  layer3[[i]][which(layer3[[i]]==-7169)] <- 0
}

##

layer4 <- sapply(j, `[[`,"layer 4")

pdgCode4 <- sapply(j, `[[`,"pdgCode")
n <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))

length(n)

layer4 <- layer4[-n]
pdgCode4 <- pdgCode4[-n]

for(i in 1:length(layer4)){
  layer4[[i]][which(layer4[[i]]==-7169)] <- 0
}

##

layer5 <- sapply(j, `[[`,"layer 5")

pdgCode5 <- sapply(j, `[[`,"pdgCode")
n <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))

length(n)

layer5 <- layer5[-n]
pdgCode5 <- pdgCode5[-n]

for(i in 1:length(layer5)){
  layer5[[i]][which(layer5[[i]]==-7169)] <- 0
}

##

```






















