---
title: "Final thesis plots and fixes"
author: "Gerhard Viljoen"
date: "05/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
load("C:/Users/Gerhard/Documents/msc-thesis-data/aux_.rdata")
load("C:/Users/Gerhard/Documents/msc-thesis-data/meta.rdata")
load("C:/Users/Gerhard/Documents/msc-thesis-data/y.rdata")
```


```{r}
names(aux)
names(meta)
```

```{r}
require(ggplot2)
require(latex2exp)

aux$dEdX <- as.numeric(aux$dEdX)
aux$P <- as.numeric(aux$P)

dedx_plot <- data.frame(cbind(aux$P,aux$dEdX))

names(dedx_plot) <- c("P","dEdX")

dedx_plot$`Particle ID` <- factor(ifelse(y==1,"electron","pion"))

# levels(dedx_plot$`Particle ID`) <- c(electron=TeX("$\\textit{e}$"),pion=TeX("$\\textit{\\pi}$"))

particle_names = list("electron" = TeX("$\\textit{e}$"), "pion" = TeX("$\\textit{\\pi}$"))

particle_labeler <- function(variable,value){
  return(particle_names[value])
}                    

require(ggExtra)   

x = hist(dedx_plot$P,breaks = 0:100)
x = x$mids
y = hist(dedx_plot$P,breaks=0:100)
y = y$mids

#install.packages("viridis")  # Install
require("viridis") 


ggplot(dedx_plot[(as.character(dedx_plot$`Particle ID`)=="electron"&dedx_plot$P>=1.5)|(as.character(dedx_plot$`Particle ID`)=="pion"&dedx_plot$P>=2),],aes(P,dEdX))+geom_hex(bins=1000)+facet_wrap(~`Particle ID`,labeller = particle_labeler)+
  theme( axis.title.y =element_text(size=12,  family="serif"))+
  theme( axis.title.x =element_text(size=12,  family="serif"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.01))+
  theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+xlab(TeX("$\\textit{p}\\,(GeV/\\textit{c})$"))+
  ylab(TeX("$\\frac{d\\textit{E}}{d\\textit{x}}\\,$ ( TPC signal , arb. units )"))+ 
       theme(strip.text.x = element_text(size = 12, family = "serif"))+
  scale_fill_viridis()+theme(legend.position = c(0.9, 0.7),
                                                           legend.title = element_text(size=12,  family="serif"))

p <- ggplot(dedx_plot[(as.character(dedx_plot$`Particle ID`)=="electron"&dedx_plot$P>=1.5)|(as.character(dedx_plot$`Particle ID`)=="pion"&dedx_plot$P>=2),],aes(P,dEdX))+geom_point()+geom_density_2d()+facet_wrap(~`Particle ID`,labeller = particle_labeler)+
  theme( axis.title.y =element_text(size=12,  family="serif"))+
  theme( axis.title.x =element_text(size=12,  family="serif"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.01))+
  theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+xlab(TeX("$\\textit{p}\\,(GeV/\\textit{c})$"))+
  ylab(TeX("$\\frac{d\\textit{E}}{d\\textit{x}}\\,$ ( TPC signal , arb. units )"))+ 
       theme(strip.text.x = element_text(size = 12, family = "serif"))+
  scale_fill_viridis()+theme(legend.position = c(0.9, 0.7),
                                                           legend.title = element_text(size=12,  family="serif"))

p
```


```{r}
y <- data.frame(y)
pt_pid <- data.frame(cbind(aux$P,aux$PT,ifelse(y$y==0,"pion","electron")))
head(pt_pid)
pt_pid$X1 <- as.numeric(as.character(pt_pid$X1))
pt_pid$X2 <- as.numeric(as.character(pt_pid$X2))
pt_pid$X3 <- as.factor(unlist(pt_pid$X3))
names(pt_pid) <- c("P","Pt","Particle ID")
```

```{r}
n = 6
h1 <- hist(pt_pid$Pt[as.character(pt_pid$`Particle ID`)=="electron"],breaks=n)
           # breaks = c(1.5,2.5,3.5,4.5,5.5,6.5))
h2 <- hist(pt_pid$Pt[as.character(pt_pid$`Particle ID`)=="pion"],breaks=n)
           # breaks=c(1.5,2.5,3.5,4.5,5.5,6.5))

h1$mids==h2$mids

x_elec = h1$mids
x_pion = h2$mids

y_elec = h1$counts
y_pion = h2$counts

df1 <- data.frame(cbind(x_elec,y_elec))
df2 <- data.frame(cbind(x_pion,y_pion))

names(df1) <- names(df2) <- c("Pt","counts")

df <- rbind(df1,df2)
df$`Particle ID` <- c(rep("electron",length(x_elec)),rep("pion",length(x_pion)))

require(ggplot2)
require(latex2exp)

fancy_scientific <- function(l) {
     l <- format(l, scientific = TRUE)
     l <- gsub("^(.*)e", "'\\1'e", l)
     l <- gsub("e", "%*%10^", l)
     parse(text=l)
}

require(extrafont)
# font_import()
# loadfonts(device = "win")

# windowsFonts()
require(MASS)
require(scales)

breaks <- 10^(1:7)
minor_breaks <- rep(1:9, 21)*(10^rep(1:7, each=9))

ggplot(data=df,aes(x=Pt,y=counts,color=`Particle ID`))+xlab(TeX("$\\textit{p}_T (GeV/\\textit{c})$"))+geom_point()+
scale_y_continuous(trans='log10',labels = fancy_scientific,limits=c(10^0, 10^7),breaks = breaks, minor_breaks = minor_breaks)+
  theme( axis.title.x =element_text(size=12,  family="serif"))+ylab(TeX("N"))+
  theme( axis.title.y =element_text(size=12,  family="serif"))+geom_errorbar(ymin=df$counts+
                                                                               sqrt(df$counts),
                                                                             ymax=df$counts-sqrt(df$counts))+
  geom_errorbarh(aes(xmin=df$Pt-0.5,xmax=df$Pt+0.5))+theme(legend.position = c(0.9, 0.85),legend.text = 
                                                             element_text(size=12,  family="serif"),
                                                           legend.title = element_text(size=12,  family="serif"))+ theme( axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.01))+
  theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+
  theme(legend.box.background = element_rect(colour = "black"),
        legend.background = element_blank(),legend.key = element_blank())+
  annotation_logticks(base=10,sides = "l")
  
```

```{r}

# scale_y_log10() geom_step()+ +geom_point()

breaks <- c(1,2,3,4,5,7,10,15,20)
# minor_breaks <- rep(0:2, 21)*(10^rep(0:2, each=9))

ggplot(data=data.frame(cbind(h1$mids,h2$counts/h1$counts)),aes(x=h1$mids,y=h2$counts/h1$counts))+geom_point()+
  ggtitle(element_blank())+xlab(TeX("\\textit{p}_T (GeV/\\textit{c})"))+ylab(TeX('Relative $\\,\\pi$ abundance: $\\,\\,(\\,\\frac{N_{\\pi}}{N_e}\\,)$'))+scale_y_continuous(trans='log10',limits=c(.1, 30),breaks=breaks)+
  geom_errorbar(aes(ymin=(h2$counts/h1$counts)-sqrt(h2$counts/h1$counts),ymax=(h2$counts/h1$counts)+sqrt(h2$counts/h1$counts),width=.05))+
  geom_errorbarh(aes(xmin=h1$mids-0.5,xmax=h1$mids+0.5))+
  theme( axis.title.x =element_text(size=12,  family="serif"))+
  theme( axis.title.y =element_text(size=12,  family="serif"))+
  theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+ theme( axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.01))

```

```{r}
rm(list=ls())
load("C:/Users/Gerhard/Documents/msc-thesis-data/y.rdata")
load("C:/Users/Gerhard/Documents/msc-thesis-data/x.rdata")
dim(x) <- c(6573905,17,24)
ph <- apply(x, 1, colSums)

ph_elec_mean <- colMeans(t(ph)[which(y==1),])
ph_pi_mean <- colMeans(t(ph)[which(y==0),])
ph <- cbind(c(ph_elec_mean,ph_pi_mean),rep(c(1,0),each=24))
ph <- setNames(data.frame(ph),c("Pulse height (mV)","Particle ID")) 
ph$`Particle ID` <- factor(ifelse(ph$`Particle ID`==1,"electron","pion"))


ph$`Drift time (us)` <- seq(from=0,to=2.4,length.out=24)

require(ggplot2)

require(latex2exp)

ggplot(ph,aes(x=`Drift time (us)`,y=`Pulse height (mV)`,color=`Particle ID`))+geom_line()+geom_point()+xlim(c(0,2.8))+
  xlab(TeX("Drift time ($\\mu$s)"))+ylab(TeX("Average pulse height$\\,\\,\\,\\,(mV)$"))+
  theme( axis.title.x =element_text(size=12,  family="serif"))+
  theme( axis.title.y =element_text(size=12,  family="serif"))+
  theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+ theme( axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.02,linetype = "solid"))+
  theme(legend.box.background = element_rect(colour = "black",linetype = "solid"),
        legend.background = element_blank(),legend.key = element_blank())+theme(legend.position = c(0.85, 0.86),legend.text = 
                                                             element_text(size=12,  family="serif"),
                                                           legend.title = element_text(size=12,  family="serif"))+
  scale_y_continuous(breaks =seq(0,200,by=10),limits = c(0,200))+scale_x_continuous(breaks = 0.2*0:12)
```


```{r}
rm(list=ls())
```

```{r}
# d <- read.csv("C:/Users/gerhard/Documents/Msc-thesis/Code/statistical_analysis/Networks Compared.csv",sep=";",header=T)
```


```{r}
rm(list=ls())
dat <- read.csv("C:/Users/gerhard/Documents/Msc-thesis/Code/statistical_analysis/Pion_efficiency_results_incremental_training.csv",sep=";",header=T)

require(dplyr)

dat <- tribble(
  ~P, ~pi_eff_unseen, ~pi_eff_seen,
  1.5, NA, 0.012,
  2.5, 0.014,0.0112,
  3.5, 0.0116,0.0151,
  4.5,NA,NA,
  5.5,NA,NA)

require(reshape2)

dat <- melt(dat,id.vars = "P")

require(ggplot2)

ggplot(dat,aes(P,value,color=variable))+geom_point()+
  geom_errorbarh(xmin=dat$P-0.5,xmax=dat$P+0.5)

#TODO: get plot data from publication

```

```{r}
# detach("package:MASS", unload=TRUE)
rm(list=ls())
d <- read.csv("C:/Users/gerhard/Documents/Msc-thesis/Code/statistical_analysis/Networks Compared.csv",sep=";",header=T)

names(d)

d$Convolutional[d$Convolutional]

require(dplyr)

pi_eff_by_num_dense_layers <- d %>%
  subset(is.na(Convolutional)==T) %>%
  dplyr::select(Model.Number,Layer.Number,Pion.Efficiency) %>%
  group_by(Model.Number) %>%
  mutate(num_layers=n())

head(pi_eff_by_num_dense_layers)

pi_eff_by_num_dense_layers <- unique(pi_eff_by_num_dense_layers)

pi_eff_by_num_dense_layers <- pi_eff_by_num_dense_layers[,-c(1,2)]

#pi_eff_by_num_dense_layers <- pi_eff_by_num_dense_layers[-289,]

pi_eff_by_num_dense_layers$Pion.Efficiency <- as.character(pi_eff_by_num_dense_layers$Pion.Efficiency )

require(stringr)

head(d)

pi_eff_by_num_convolutional_layers <- d %>%
  subset(Convolutional==T) %>%
  dplyr::select(Model.Number,Layer.Number,Pion.Efficiency) %>%
  group_by(Model.Number) %>%
  mutate(num_layers=n())

pi_eff_by_num_convolutional_layers$Pion.Efficiency <- as.numeric(str_replace(string=as.character(pi_eff_by_num_convolutional_layers$Pion.Efficiency),pattern=",",replacement="."))

pi_eff_by_num_convolutional_layers <- unique(pi_eff_by_num_convolutional_layers)

pi_eff_by_num_convolutional_layers <- pi_eff_by_num_convolutional_layers[,-c(1,2)]

#pi_eff_by_num_convolutional_layers <- pi_eff_by_num_convolutional_layers[-289,]

pi_eff_by_num_convolutional_layers$Pion.Efficiency <- as.character(pi_eff_by_num_convolutional_layers$Pion.Efficiency )

require(stringr)

pi_eff_by_num_convolutional_layers$Pion.Efficiency <- as.numeric(str_replace(string=as.character(pi_eff_by_num_convolutional_layers$Pion.Efficiency),pattern=",",replacement="."))

pi_eff_by_num_dense_layers$Pion.Efficiency <- as.numeric(str_replace(string=as.character(pi_eff_by_num_dense_layers$Pion.Efficiency),pattern=",",replacement="."))

pi_eff_by_num_convolutional_layers$layer_type <- as.factor("Convolutional")
pi_eff_by_num_dense_layers$layer_type <- as.factor("Dense")

pi_eff_by_num_dense_layers <- rbind(pi_eff_by_num_dense_layers,pi_eff_by_num_convolutional_layers)

require(ggplot2)
require(latex2exp)

fancy_scientific <- function(l) {
     l <- format(l, scientific = TRUE)
     l <- gsub("^(.*)e", "'\\1'e", l)
     l <- gsub("e", "%*%10^", l)
     parse(text=l)
}

# require(scales)

pi_eff_by_num_dense_layers$Pion.Efficiency <- as.numeric(as.character(pi_eff_by_num_dense_layers$Pion.Efficiency))

# pi_eff_by_num_dense_layers <- as.numeric(as.character(pi_eff_by_num_dense_layers))
# 
# pi_eff_by_num_dense_layers <- data.frame(pi_eff_by_num_dense_layers)

names(pi_eff_by_num_dense_layers)[3] <- "Layer Type"

ggplot(pi_eff_by_num_dense_layers,aes(num_layers,Pion.Efficiency,col=`Layer Type`))+ geom_point()+
  theme(panel.background = element_blank())+theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+ theme( axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.02,linetype = "solid"))+
  theme(legend.box.background = element_rect(colour = "black",linetype = "solid"))+
  scale_y_continuous(trans="log10",breaks =c(0.001,0.01,0.1*c(0,1,2,3,4,5,7,10)),minor_breaks =c(0.002,0.003,0.004,0.005,0.006,0.007,0.008,0.009,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.6,0.8,0.9,0.45,0.35,0.25,0.11,
                                                                                                 0.12,0.13,0.14,0.15,0.16,0.17,0.18,0.19,0.9),labels = fancy_scientific,limits = c(0.001,1))+
  theme( axis.title.x =element_text(size=12,  family="serif"))+
  theme( axis.title.y =element_text(size=12,  family="serif"))+
  ylab(
    TeX("$\\epsilon_{\\pi}$")
  )+
  xlab(TeX("$N_{layers}$"))+facet_wrap(~`Layer Type`,scales="free_x")+
  theme(legend.box.background = element_rect(colour = "black",linetype = "solid"),
        legend.background = element_blank(),legend.key = element_blank())+theme(legend.position = c(0.89, 0.86),legend.text = 
                                                             element_text(size=12,  family="serif"),
                                                           legend.title = element_text(size=12,  family="serif"))+ 
       theme(strip.text.x = element_text(size = 12, family = "serif"))+theme(legend.title = element_text(size=12,  family="serif"))+ theme(legend.position = "none")

```


```{r}
names(d)

require(plotly)

p_3d <- d %>%
  dplyr::select(Model.Number,Learning.Rate,Epochs,Pion.Efficiency,Optimizer,Batch.Size,Layer.Number,Convolutional) %>%
  group_by(Model.Number) %>%
  mutate(convolutional_layers=length(which(Convolutional))) %>%
  mutate(`Total N layers`=max(Layer.Number)) %>%
  unique() %>%
  na.omit() %>%
  data.frame()

p_3d <- p_3d[,-c(1,7,8)]

require(stringr)

p_3d <- data.frame(p_3d)

p_3d$Learning.Rate <- as.numeric(str_replace(string=as.character(p_3d$Learning.Rate),pattern = ",","."))
p_3d$Pion.Efficiency <- as.numeric(str_replace(string=as.character(p_3d$Pion.Efficiency),pattern = ",","."))

p_3d <- unique(p_3d)

# p_3d <- expand.grid(p_3d)

require(ggExtra)

# p <- ggplot(p_3d,aes(x=Epochs,y=Learning.Rate,color=Batch.Size))+geom_jitter()+scale_y_continuous(trans='log10')+
#   scale_fill_distiller(palette=4, direction=-1) 
# 
# ggMarginal(p,type="density")
# p <-ggMarginal(p,type="density")
# min(p_3d$Pion.Efficiency)


# pi_eff_by_num_convolutional_layers <- unique(pi_eff_by_num_convolutional_layers)
# p_3d <- unique(p_3d)

p_3d$Learning.Rate <- as.character(p_3d$Learning.Rate)

    

# particle_names = list("0.01" = TeX("10^{-1}"),"1e-05"=TeX("10^{-5}"), "1e-07"= TeX("10^{-7}"),"1e-06"=TeX("10^{-6}"))
# 
# particle_labeler <- function(variable,value){
#   return(particle_names[value])
# }

p_3d$Learning.Rate <- as.factor(p_3d$Learning.Rate)

# levels(p_3d$Learning.Rate) <- c("0.01" = TeX("$\\eta=10^{-1}$"),"1e-05"=TeX("$\\eta=10^{-5}$"),"1e-06"= TeX("$\\eta=10^{-6}$"),"1e-07"= TeX("$\\eta=10^{-7}$"))

# levels(p_3d$Learning.Rate) <- c("0.01" = TeX("$\\eta=0.01$"),"1e-05"=TeX("$\\eta=0.000001$"),"1e-06"= TeX("$\\eta=0.0000001$"),"1e-07"= TeX("$\\eta=0.00000001$"))

levels(p_3d$Learning.Rate) <- c("0.01" = "eta==~10^-2","1e-05"="eta==~10^-5","1e-06"= "eta==~10^-6","1e-07"= "eta==~10^-7")

as.character(p_3d$Learning.Rate)

p_3d$Batch.Size <- as.factor(p_3d$Batch.Size)

names(p_3d)[c(6,7)] <- c("Number of conv. layers","Total number of layers")

ggplot(p_3d,aes(x=Epochs,y=Pion.Efficiency,size=`Total number of layers`,shape=Optimizer,color=`Number of conv. layers`))+geom_jitter(alpha=6/10)+facet_wrap(~factor(Learning.Rate),labeller = label_parsed)+
  theme(panel.background = element_blank())+theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+ theme( axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.02,linetype = "solid"))+
  ylab(expression(epsilon[pi]))+xlab("Epochs")+
  theme( axis.title.x =element_text(size=12,  family="serif"))+
  theme( axis.title.y =element_text(size=12,  family="serif"))+
  scale_y_continuous(trans="log10",breaks =c(0.001,0.01,0.1*c(0,1,2,5,7,10)),labels = fancy_scientific,limits = c(0.01,1))+
  theme(legend.box.background = element_rect(colour = "black",linetype = "solid"),
        legend.background = element_blank(),legend.key = element_blank())+theme(legend.text = 
                                                             element_text(size=12,  family="serif"),
                                                           legend.title = element_text(size=12,  family="serif"))

#+scale_y_continuous(trans='log10')

```




```{r}
mydata = data.frame(x=rnorm(4), y=runif(4), tau=c(0,0,1,1))
ggplot(mydata) + geom_point(aes(x=x, y=y)) +
         facet_grid(~ tau,labeller = label_bquote(tau ^ .(x)))

labNames <- c('xLab','yLab')
xlab <- bquote(.(labNames[1]) ~ x^2)
ylab <- bquote(.(labNames[2]) ~ y^2)
plot(c(1:10), xlab = xlab, ylab = ylab)
```

```{r}
rm(list=ls())

load("C:/Users/gerhard/documents/msc-thesis/Thesis/misc/random_images/geant_preds.rdata")

length(sim_preds)

hist(sim_preds,breaks=1000)
```



#Real V Geant

```{r}
rm(list=ls())

load("c:/Users/gerhard/Documents/msc-thesis-data/hijing-sim/sim_x_full.rdata")
load("c:/Users/gerhard/Documents/msc-thesis-data/hijing-sim/real_x_full.rdata")
```

```{r}
require(abind)
x_train = abind(real_x,sim_x,along=1)

y_train = c(rep(1,dim(real_x)[1]),rep(0,dim(sim_x)[1]))

dim(x_train) = c(dim(x_train),1)

require(keras)
model <- keras_model_sequential() %>%
  layer_conv_2d(16, kernel_size = c(4,4),activation = "tanh") %>%
  layer_max_pooling_2d() %>%
  layer_conv_2d(32, kernel_size = c(4,4),activation = "tanh") %>%
  layer_max_pooling_2d() %>%
  layer_flatten() %>%
  layer_dense(512,"tanh") %>%
  layer_dense(256,"tanh") %>%
  layer_dense(128,"tanh") %>%
  layer_dense(1, "sigmoid")

model %>%
  compile(
    loss="binary_crossentropy",
    optimizer_adam(0.00001),
    metrics="acc"
    
  )
  
history <- model %>%
  fit(x_train,
      y_train,
      batch_size=32,
      verbose=2,
      epochs=30,
      shuffle=TRUE)

png("C:/Users/gerhard/documents/MSc-thesis/NEW/ML/geant_v_real_FINAL.png")
plot(history)
dev.off()
```


```{r}
m <- setNames(data.frame(cbind(1:history$params$epochs, history$metrics$loss, history$metrics$acc)),c("epochs","loss","accuracy")) 
```



```{r}
require(ggplot2)

require(reshape2)

m <- melt(m,id.vars ="epochs")

ggplot(m,aes(x=epochs,y=value,color=variable))+geom_line()+geom_point()+facet_wrap(~variable)+scale_y_continuous(limits=c(0,1))
```


```{r}
preds <- data.frame(cbind(predict(model,x_train)),ifelse(y_train==1,"real","geant"))

require(ggplot2)

names(preds) <- c("P(real)","Datatype")

preds$`P(real)` <- as.numeric(as.character(preds$`P(real)`))

preds$Datatype <- as.factor(preds$Datatype)

fancy_scientific <- function(l) {
     l <- format(l, scientific = TRUE)
     l <- gsub("^(.*)e", "'\\1'e", l)
     l <- gsub("e", "%*%10^", l)
     parse(text=l)
}

require(dplyr)

ggplot(preds,aes(x=preds$`P(real)`,fill=Datatype,colour=Datatype))+geom_bar(stat="bin", position = position_dodge())+
  xlab("P(real)")+scale_y_continuous(trans="log",labels = fancy_scientific)+
  theme(panel.background = element_blank())+theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+ theme( axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.02,linetype = "solid"))+
  theme( axis.title.x =element_text(size=12,  family="serif"))+
  theme( axis.title.y =element_text(size=12,  family="serif"))+
  theme(legend.box.background = element_rect(colour = "black",linetype = "solid"),
        legend.background = element_blank(),legend.key = element_blank())+theme(legend.text = 
                                                             element_text(size=12,  family="serif"),
                                                           legend.title = element_text(size=12,  family="serif"),
                                                           legend.position = c(0.7,0.85))
```


```{r}
baseurl <- "C:/Users/gerhard/documents/Msc-thesis/code/"
NN <- data.frame(read.csv(paste0(baseurl,"NN.csv"),header = F))
LQ7D <- data.frame(read.csv(paste0(baseurl,"LQ7D.csv"),header = F))

NN$V2 > LQ7D$V2

LQ3D <- data.frame(read.csv(paste0(baseurl,"LQ3D.csv"),header = F))
LQ2D <- data.frame(read.csv(paste0(baseurl,"LQ2D.csv"),header = F))
LQ1D <- data.frame(read.csv(paste0(baseurl,"LQ1D.csv"),header = F))
TruncMean <- data.frame(read.csv(paste0(baseurl,"Trunc Mean.csv"),header = F))

myResult <- tribble(
  ~GeV, ~pi_eff_unseen, ~pi_eff_seen,
  1.5, NA, 0.012,
  2.5, 0.014,0.0112,
  3.5, 0.0116,0.0151,
  4.5,NA,NA,
  5.5,NA,NA)

names(myResult) <- c("GeV","This thesis: unseen","This thesis: seen")

myResult$GeV <- as.numeric(as.character(myResult$GeV))

myResult <- melt(myResult,id.vars = "GeV")

names(myResult) <- c("GeV","model","pi_efficiency")

names(NN) <- c("GeV","pi_efficiency")
names(LQ7D) <- c("GeV","pi_efficiency")
names(LQ3D) <- c("GeV","pi_efficiency")
names(LQ2D) <- c("GeV","pi_efficiency")
names(LQ1D) <- c("GeV","pi_efficiency")
names(TruncMean) <- c("GeV","pi_efficiency")

NN$model <- "NN"
LQ7D$model <- "LQ7D"
LQ3D$model <- "LQ3D"
LQ2D$model <- "LQ2D"
LQ1D$model <- "LQ1D"
TruncMean$model <- "Truncated Mean"

myResult <- myResult[-c(1,4,5,9,10),]

myResult$GeV <- as.numeric(as.character(myResult$GeV))
myResult$pi_efficiency <- as.numeric(as.character(myResult$pi_efficiency))
myResult$model <- as.character(myResult$model)

NN$GeV <- as.numeric(as.character(NN$GeV))
NN$pi_efficiency <- as.numeric(as.character(NN$pi_efficiency))
NN$model <- as.character(NN$model)

LQ7D$GeV <- as.numeric(as.character(LQ7D$GeV))
LQ7D$pi_efficiency <- as.numeric(as.character(LQ7D$pi_efficiency))
LQ7D$model <- as.character(LQ7D$model)

NN$pi_efficiency > LQ7D$pi_efficiency

LQ3D$GeV <- as.numeric(as.character(LQ3D$GeV))
LQ3D$pi_efficiency <- as.numeric(as.character(LQ3D$pi_efficiency))
LQ3D$model <- as.character(LQ3D$model)

LQ2D$GeV <- as.numeric(as.character(LQ2D$GeV))
LQ2D$pi_efficiency <- as.numeric(as.character(LQ2D$pi_efficiency))
LQ2D$model <- as.character(LQ2D$model)

LQ1D$GeV <- as.numeric(as.character(LQ1D$GeV))
LQ1D$pi_efficiency <- as.numeric(as.character(LQ1D$pi_efficiency))
LQ1D$model <- as.character(LQ1D$model)

TruncMean$GeV <- as.numeric(as.character(TruncMean$GeV))
TruncMean$pi_efficiency <- as.numeric(as.character(TruncMean$pi_efficiency))
TruncMean$model <- as.character(TruncMean$model)

TruncMean$GeV[length(TruncMean$GeV)] <- 4.6
LQ1D$GeV[length(LQ1D$GeV)] <- 4.6

res <- data.frame(rbind(myResult,
                        NN,
             LQ7D,
             LQ3D,
             LQ2D,
             LQ1D,
             TruncMean))

add <- res[1:5,]

xmin = c(
res$GeV[1:5]-0.5,
res$GeV[6:65]-c(
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25),
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25),
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25,
    0.35),
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25,
    0.35),
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25,
    0.35,
    0.6),
  
    c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25,
    0.35,
    0.6)
                
                
                )
  
)


xmax = c(
res$GeV[1:5]+0.5,
res$GeV[6:65]+c(
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25),
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25),
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25,
    0.35),
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25,
    0.35),
  
  c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25,
    0.35,
    1.4),
  
    c(0.2,
                0.1,
                0.1,
                0.1,
                0.1,
                0.2,
                0.2,
                0.25,
                0.25,
    0.35,
    1.4)
                
                
                )
  
)


res$pi_efficiency <- round(res$pi_efficiency,4)

res$GeV <- round(res$GeV,1)
# res$GeV[nrow(res)] <- 4.6

require(latex2exp)

ggplot(res,aes(x=GeV,y=pi_efficiency,color=model))+geom_point()+scale_y_continuous(trans="log10",
                                                                                   limits = c(10^-3,10^1),
                                                                                   labels = fancy_scientific)+
  geom_point(data=add,aes(x=add$GeV,y=add$pi_efficiency,size=5,alpha=0.8))+geom_errorbarh(xmin=xmin,xmax=xmax)+
  scale_x_continuous(limits=c(0,6))+scale_alpha(guide=F)+scale_size(guide=F)+
  theme(panel.background = element_blank())+theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+ theme( axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.02,linetype = "solid"))+
  ylab(expression(epsilon[pi]))+xlab(TeX("$\\textit{p}\\,(GeV/\\textit{c})$"))+
  theme( axis.title.x =element_text(size=12,  family="serif"))+
  theme( axis.title.y =element_text(size=12,  family="serif"))+theme(legend.position = c(0.8, 0.79),
                                                           legend.title = element_blank(),
                                                           legend.text = element_text(size=8,family = "serif"),
                                                           legend.background = element_rect(colour = "black"))+
  annotation_logticks(base=10,side="lr")+guides(color=guide_legend(ncol=2))

# +scale_alpha_manual(values=c("This thesis: seen"=1, "This thesis: unseen"="1", 
                                                                # "NN"="0.5","LQ7D"="0.5","LQ3D"="0.5","LQ1D"="0.5","Truncated Mean"="0.5"))
```


```{r}
# install.packages('digitize') #download the digitize package
library(digitize) #load the digitize package into the workspace
```


```{r}
# cal = ReadAndCal("C:/Users/gerhard/documents/msc-thesis/thesis/misc/random_images/trd_res.png")
```

# Real data from Yvonne Pachmayer:

```{r}
lq1d_x <- c( 0.4246237,
   0.5985138,
   0.7952877,
   0.9949122,
   1.195459,
   1.439668,
   1.781109,
   2.220042,
   2.719777,
   3.386895,
   4.633428)
# ,
#    6.708676,
#    8.769783)

lq1d_y <- c(0.05995413,
   0.02618553,
   0.01798861,
   0.01464972,
   0.0130867,
   0.01180527,
   0.01225982,
   0.01265445,
   0.01365352,
   0.015793,
   0.02082409)
   # ,
   # 0.02549183,
   # 0.0432357)

lq1d_xmin <- c(0.1746237,
   0.09851377,
   0.0952877,
   0.09491219,
   0.09545939,
   0.1396684,
   0.1811093,
   0.2200421,
   0.2197765,
   0.3868948,
   0.6334283)
# ,
#    0.7086763,
#    0.7697825)

lq1d_ymin <- c(0.00041929,
   0.0001626565,
   0.0001379372,
   0.0001425759,
   0.0001578967,
   0.0001499509,
   0.0001780204,
   0.0002343499,
   0.0003606809,
   0.000456453,
   0.0008567724)
   # ,
   # 0.002538123,
   # 0.007183467)

lq1d_xmax <- c(0.07537628,
   0.1014862,
   0.1047123,
   0.1050878,
   0.1045406,
   0.1603316,
   0.2188907,
   0.2799579,
   0.2802235,
   0.6131052,
   1.366572)
# ,
#    1.291324,
#    1.230217)

lq1d_ymax <- c(0.000421131,
   0.0001633114,
   0.0001386347,
   0.0001434929,
   0.0001591597,
   0.0001512152,
   0.0001797422,
   0.0002372427,
   0.00036706,
   0.0004652737,
   0.0008804119)
   # ,
   # 0.002713623,
   # 0.008034492)

###

lq2d_x <- c(0.4246237,
   0.5985138,
   0.7952877,
   0.9949122,
   1.195459,
   1.439668,
   1.781109,
   2.220042,
   2.719777,
   3.386895)
  # 0,
   # 6.708676,
   # 8.769783)

lq2d_y <- c( 0.0182008,
   0.008690082,
   0.007186723,
   0.006815969,
   0.006465314,
   0.006566484,
   0.007098259,
   0.008929275,
   0.008960263,
   0.01155957)
 #  0,
   # 0.02786934,
   # 0.01497006)

lq2d_xmin <- c(
   0.1746237,
   0.09851377,
   0.0952877,
   0.09491219,
   0.09545939,
   0.1396684,
   0.1811093,
   0.2200421,
   0.2197765,
   0.3868948)
# ,
#    0,
#    0.7086763,
#    0.7697825)

lq2d_ymin <- c(0.0002555716,
   0.0001013664,
   9.360688e-05,
   0.0001038548,
   0.0001180569,
   0.0001185432,
   0.0001431494,
   0.0002072308,
   0.0003064928,
   0.0004085486)
   # ,
   # 0,
   # 0.002757274,
   # 0.004251596)

lq2d_xmax <- c(0.07537628,
   0.1014862,
   0.1047123,
   0.1050878,
   0.1045406,
   0.1603316,
   0.2188907,
   0.2799579,
   0.2802235,
   0.6131052)
# ,
#    0,
#    1.291324,
#    1.230217)


lq2d_ymax <- c(0.0002579389,
   0.0001021526,
   9.442127e-05,
   0.000104914,
   0.0001194995,
   0.0001199791,
   0.000145084,
   0.0002104578,
   0.0003135798,
   0.0004182893)
   # ,
   # 0,
   # 0.002946113,
   # 0.005231558)

truncmean_x <- c(0.4282423,
   0.6000849,
   0.7962816,
   0.9943921,
   1.194152,
   1.435419,
   1.775172,
   2.208079,
   2.715589,
   3.39307,
   4.66792)

truncmean_y <- c(0.01087039,
   0.008806097,
   0.009541358,
   0.01061348,
   0.01210252,
   0.01536979,
   0.02205133,
   0.0257691,
   0.02921964,
   0.03458587,
   0.04394453)

truncmean_xmin <- c(0.1782423,
   0.1000849,
   0.09628164,
   0.09439208,
   0.09415187,
   0.1354187,
   0.1751718,
   0.2080794,
   0.2155892,
   0.3930699,
   0.66792)

truncmean_ymin <- c(0.0002332891,
   0.0001339876,
   0.0001392597,
   0.000162656,
   0.0002041303,
   0.0002315973,
   0.0003275415,
   0.0004846174,
   0.0008150425,
   0.001053386,
   0.001840933)

truncmean_xmax <- c(0.07175772,
   0.09991508,
   0.1037184,
   0.1056079,
   0.1058481,
   0.1645813,
   0.2248282,
   0.2919206,
   0.2844108,
   0.6069301,
   1.33208)

truncmean_ymax <- c(0.0002332891,
   0.0001339876,
   0.0001392597,
   0.000162656,
   0.0002041303,
   0.0002315973,
   0.0003275415,
   0.0004846174,
   0.0008150425,
   0.001053386,
   0.001840933)

lq3d_x <- c(0.4246237,
   0.5985138,
   0.7952877,
   0.9949122,
   1.195459,
   1.439668,
   1.781109,
   2.220042,
   2.719777,
   3.386895)
# ,
#    0,
#    6.708676,
#    8.769783)

lq3d_y <- c(0.008587062,
   0.004324015,
   0.003892957,
   0.004236479,
   0.00420567,
   0.004426742,
   0.005222723,
   0.006813136,
   0.007418575,
   0.01003108)
# ,
#    0,
#    0.03515625,
#    0.01610306)

lq3d_xmin <- c(0.1746237,
   0.09851377,
   0.0952877,
   0.09491219,
   0.09545939,
   0.1396684,
   0.1811093,
   0.2200421,
   0.2197765,
   0.3868948)
# ,
#    0,
#    0.7086763,
#    0.7697825)

lq3d_ymin <- c( 0.0001918521,
   7.709787e-05,
   7.38549e-05,
   8.741507e-05,
   0.0001012156,
   0.0001031333,
   0.0001297245,
   0.0001905773,
   0.0002929545,
   0.0003988052)
# ,
#    0,
#    0.003224016,
#    0.004571037)

lq3d_xmax <- c(0.07537628,
   0.1014862,
   0.1047123,
   0.1050878,
   0.1045406,
   0.1603316,
   0.2188907,
   0.2799579,
   0.2802235,
   0.6131052)
# ,
#    0,
#    1.291324,
#    1.230217)

lq3d_ymax <- c(0.0001947267,
   7.802294e-05,
   7.479652e-05,
   8.862788e-05,
   0.0001028577,
   0.0001047534,
   0.0001318987,
   0.0001941726,
   0.0003008153,
   0.0004095506)
# ,
#    0,
#    0.003425921,
#    0.005622436)

lq7d_x <- c(0.4246237,
   0.5985138,
   0.7952877,
   0.9949122,
   1.195459,
   1.439668,
   1.781109,
   2.220042,
   2.719777)
# ,
#    0,
#    0,
#    6.708676,
#    8.769783)

lq7d_y <- c(0.002198844,
   0.00169033,
   0.001693018,
   0.002433176,
   0.0027795,
   0.003243855,
   0.004485803,
   0.00581661,
   0.007621758)
# ,
#    0,
#    0,
#    0.02690326,
#    0.09782609)

lq7d_xmin <- c(0.1746237,
   0.09851377,
   0.0952877,
   0.09491219,
   0.09545939,
   0.1396684,
   0.1811093,
   0.2200421,
   0.2197765)
# ,
#    0,
#    0,
#    0.7086763,
#    0.7697825)

lq7d_ymin <- c( 0.0001454883,
   7.771092e-05,
   8.019785e-05,
   0.0001092691,
   0.0001337509,
   0.000140521,
   0.0001858729,
   0.000263229,
   0.0004301765)
# ,
#    0,
#    0,
#    0.003696484,
#    0.01475164)

lq7d_xmax <- c(0.07537628,
   0.1014862,
   0.1047123,
   0.1050878,
   0.1045406,
   0.1603316,
   0.2188907,
   0.2799579,
   0.2802235)
# ,
#    0,
#    0,
#    1.291324,
#    1.230217)

lq7d_ymax <- c(0.0001521873,
   8.016433e-05,
   8.280832e-05,
   0.0001126328,
   0.0001381718,
   0.0001446861,
   0.00019113,
   0.0002713692,
   0.0004468621)
# ,
#    0,
#    0,
#    0.004058301,
#    0.01620625)

nn_x <- c(0.4350755,
   0.6029244,
   0.7949052,
   0.9947967,
   1.194642,
   1.437239,
   1.776804,
   2.216097,
   2.717597)
# ,
#    0,
#    0)

nn_y <- c(0.001584595,
   0.002067708,
   0.001976303,
   0.002800063,
   0.002948037,
   0.00314751,
   0.003752736,
   0.005697906,
   0.007884761)
# ,
#    0,
#    0)

nn_xmin <- c(0.1850755,
   0.1029244,
   0.09490524,
   0.09479674,
   0.09464166,
   0.1372393,
   0.1768043,
   0.2160971,
   0.217597)
# ,
#    0,
#    0)

nn_ymin <- c(0.0001819213,
   0.0001447847,
   0.0001499419,
   0.0001954909,
   0.0002381787,
   0.0002787655,
   0.0003655312,
   0.000538673,
   0.0010679)
# ,
#    0,
#    0)

nn_xmax <- c(0.06492454,
   0.09707562,
   0.1050947,
   0.1052033,
   0.1053583,
   0.1627608,
   0.2231956,
   0.2839029,
   0.282403)
# ,
#    0,
#    0)

nn_ymax <- c(0.0001819213,
   0.0001447847,
   0.0001499419,
   0.0001954909,
   0.0002381787,
   0.0002787655,
   0.0003655312,
   0.000538673,
   0.0010679)
# ,
#    0,
#    0)


lq2d <- data.frame(cbind(lq2d_x,lq2d_y,lq2d_xmin,lq2d_xmax,lq2d_ymin,lq2d_ymax,rep("LQ2D",length(lq2d_x))))

lq1d <- data.frame(cbind(lq1d_x,lq1d_y,lq1d_xmin,lq1d_xmax,lq1d_ymin,lq1d_ymax,rep("LQ1D",length(lq1d_x))))

truncmean <- data.frame(cbind(truncmean_x,truncmean_y,truncmean_xmin,truncmean_xmax,
                              truncmean_ymin,truncmean_ymax,rep("Truncated Mean",length(truncmean_x))))

lq3d <- data.frame(cbind(lq3d_x,lq3d_y,lq3d_xmin,lq3d_xmax,lq3d_ymin,lq3d_ymax,rep("LQ3D",length(lq3d_x))))

lq7d <- data.frame(cbind(lq7d_x,lq7d_y,lq7d_xmin,lq7d_xmax,lq7d_ymin,lq7d_ymax,rep("LQ7D",length(lq7d_x))))

nn <- data.frame(cbind(nn_x,nn_y,nn_xmin,nn_xmax,nn_ymin,nn_ymax,rep("NN",length(nn_x))))

myResult <- tribble(
  ~GeV, ~pi_eff_unseen, ~pi_eff_seen,
  1.5, NA, 0.012,
  2.5, 0.014,0.0112,
  3.5, 0.0116,0.0151)

require(reshape2)

myResult <- melt(myResult,id.vars="GeV")

myResult <- na.omit(myResult)

myResult$GeV <- as.numeric(as.character(myResult$GeV))
myResult$value <- as.numeric(as.character(myResult$value))
myResult$variable <- as.factor(myResult$variable)

myResult <- myResult[,c(1,3,2)]

myResult$xmin <- 0.5
myResult$xmax <- 0.5
myResult$ymin <- 0
myResult$ymax <- 0

myResult$Model <- c(rep("CNN (this thesis, data unseen)*",2),
                    rep("CNN (this thesis, data seen)*",3))

myResult <- myResult[,-3]

for(i in 1:6){
  myResult[,i] <- as.numeric(as.character(myResult[,i]))
}

lq1d <- rbind(lq1d,setNames(lq2d,names(lq1d)),setNames(lq3d,names(lq1d)),
              setNames(lq7d,names(lq1d)),setNames(truncmean,names(lq1d)),
              setNames(nn,names(lq1d)))

names(lq1d)[7] <- "Model"

for(i in 1:6){
  lq1d[,i] <- as.numeric(as.character(lq1d[,i]))
}

require(ggplot2)

lq1d <- rbind(lq1d,setNames(myResult,names(lq1d)))

require(latex2exp)

fancy_scientific <- function(l) {
     l <- format(l, scientific = TRUE)
     l <- gsub("^(.*)e", "'\\1'e", l)
     l <- gsub("e", "%*%10^", l)
     parse(text=l)
}

ggplot(lq1d,aes(x=lq1d_x,y=lq1d_y,color=Model))+geom_point()+geom_errorbar(ymin=lq1d$lq1d_y-lq1d$lq1d_ymin,ymax=lq1d$lq1d_y+lq1d$lq1d_ymax)+
  geom_errorbarh(xmin=lq1d$lq1d_x-lq1d$lq1d_xmin,xmax=lq1d$lq1d_x+lq1d$lq1d_xmax)+
  scale_x_continuous(limits = c(0,6))+scale_y_continuous(trans="log10",limits=c(0.001,1),labels = fancy_scientific)+
  geom_point(data=myResult,aes(x=myResult$GeV,y=myResult$value),size=5,alpha=0.5)+scale_alpha(guide=F)+scale_size(guide=F)+
  theme(panel.background = element_blank())+theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+ theme( axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.02,linetype = "solid"))+
  ylab(expression(epsilon[pi]))+xlab(TeX("$\\textit{p}\\,(GeV/\\textit{c})$"))+
  theme( axis.title.x =element_text(size=12,  family="serif"))+
  theme( axis.title.y =element_text(size=12,  family="serif"))+theme(legend.position = c(0.75, 0.81),
                                                           legend.title = element_blank(),
                                                           legend.text = element_text(size=8,family = "serif"),
                                                           legend.background = element_rect(colour = "black"))+
  annotation_logticks(base=10,side="lr")+guides(color=guide_legend(ncol=2))

```



```{r}
rm(list=ls())

setwd("C:/Users/gerhard/documents/msc-thesis/code/")

vae_loss <- read.csv("vae_loss.csv")

require(ggplot2)

vae_loss <- data.frame(cbind(1:164,vae_loss))
names(vae_loss) <- c("epoch","mean(MSE + KL) loss")

ggplot(vae_loss,aes(epoch,`mean(MSE + KL) loss`))+geom_line()+scale_y_continuous(trans="log")
```

```{r}
rm(list=ls())
```



```{r}
vae <- read.csv("C:/users/gerhard/documents/msc-thesis/code/latent variable models/newvae/m15/vae_preds.csv",header=F)
real <- read.csv("C:/users/gerhard/documents/msc-thesis/code/latent variable models/newvae/m15/real_preds.csv",header=F)

# preds <- data.frame(cbind(predict(model,x_train)),ifelse(y_train==1,"real","geant"))

preds <- data.frame(rbind(vae,real))
names(preds) <- "P(real)"
preds$Datatype <- c(rep("VAE (fully connected)",nrow(vae)),rep("Real",nrow(real)))


require(ggplot2)

names(preds) <- c("P(real)","Datatype")

preds$`P(real)` <- as.numeric(as.character(preds$`P(real)`))

preds$Datatype <- as.factor(preds$Datatype)

fancy_scientific <- function(l) {
     l <- format(l, scientific = TRUE)
     l <- gsub("^(.*)e", "'\\1'e", l)
     l <- gsub("e", "%*%10^", l)
     parse(text=l)
}

require(dplyr)

ggplot(preds,aes(x=preds$`P(real)`,fill=Datatype,colour=Datatype))+geom_bar(stat="bin", position = position_dodge())+
  xlab("P(real)")+scale_y_continuous(trans="log",labels = fancy_scientific)+
  theme(panel.background = element_blank())+theme(panel.grid.major = element_line(size = 0.1, linetype = 'solid',colour = "gray90"))+
  theme(panel.grid.minor = element_line(size = 0.1, linetype = 'dashed',colour = "gray90"))+ theme( axis.line = element_line(colour = "black", 
                      size = 0.5, linetype = "solid"))+theme(axis.text = element_text(color = "black"))+
  theme(panel.background = element_rect(fill="white",color="black",size=0.02,linetype = "solid"))+
  theme( axis.title.x =element_text(size=12,  family="serif"))+
  theme( axis.title.y =element_text(size=12,  family="serif"))+
  theme(legend.box.background = element_rect(colour = "black",linetype = "solid"),
        legend.background = element_blank(),legend.key = element_blank())+theme(legend.text = 
                                                             element_text(size=12,  family="serif"),
                                                           legend.title = element_text(size=12,  family="serif"),
                                                           legend.position = c(0.5,0.85))
```




```{r}
x = seq(-10,10,length.out = 100000)
y = ifelse(x<0,0,x)
require(latex2exp)
plot(x=x,y=y,type="l",lwd=3,col="red",main=TeX("ReLU Activation function"),ylab="",xlab = TeX("$w^{T}x+b$"),family="serif")
title(ylab = TeX("$\\varphi(w^{T}x+b)$"), mgp=c(2.5,1,1), family="serif",cex.lab=1.2)
text(x=0,y=9,labels = TeX("$\\varphi(w^{T}x+b) = max(w^{T}x+b,0)$"),family="serif")
```

























