---
title: "Binary Cross Entropy"
author: "Gerhard Viljoen"
date: "1/18/2019"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#For binary classification:

```{r}
cross.entropy <- function(y,p){
  -(y * log(p,base = 10) + ((1-y)*(1 - log(1-p,base=10))))
}

#if the predicted class is 1:

y <- 1

p <- seq(0,1,0.01)

loss <- cross.entropy(y,p)

cross.entropy <- function(y,p){
  -(y * log(p,base = 10) + ((1-y)*(1 - log(1-p,base=10))))
}

loss2 <- cross.entropy(y=1,rev(p))

require(latex2exp)

plot(x=p,y=loss,  col="purple",cex=0.5, main =
       TeX("L(y,$\\hat{y}$) = -(y . log($\\hat{y}$) + (1-y) .log(1-$\\hat{y}$)))"),ylab = "Binary Cross Entropy Loss", xlab = TeX("$\\hat{y}$"),family="serif",type="l",lwd=2)
lines(x=p,y=loss2, col="cornflowerblue",lwd=2)
text(x=.15,y=1,"y=1",col="purple")
text(x=.85,y=1,"y=0",col="cornflowerblue")
```



```{r}
rm(list=ls())

x <- c(c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(14, 60, 63, 43, 30, 24, 21, 19, 17, 16, 17, 18, 19, 16, 19, 20, 19, 18, 17, 22, 30, 51, 58, 40 ),
				c(14, 66, 81, 57, 37, 30, 27, 26, 22, 26, 24, 23, 26, 25, 35, 38, 37, 37, 36, 70, 91, 193, 286, 186 ),
				c(10, 15, 16, 13, 10, 10, 10, 9, 8, 10, 10, 12, 11, 11, 13, 14, 15, 13, 20, 39, 54, 70, 86, 72 ),
				c(10, 10, 11, 9, 11, 9, 8, 6, 8, 8, 8, 11, 10, 9, 9, 11, 8, 11, 12, 12, 13, 17, 16, 16 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ),
				c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))
x <- as.numeric(unlist(x))

x <- matrix(
  data=x,ncol=24,nrow=17,byrow=T)

```
















