---
title: "Meta-compression"
author: "Gerhard Viljoen"
date: "30/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,eval=F}
rm(list=ls())

require(jsonlite)
require(readtext)

#PDG codes
# pdg.elec <- c(11,-11)
# pdg.pion <- c(-211,211)

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265309", pattern="*json", full.names=T, recursive=T)

j <- fromJSON(files[1])

for(i in 2:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265309"
# }
  j <- c(j,f)
}



files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265332", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265332"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265334", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265334"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265335", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265335"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265336", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  
#   if(length(f)!=0){
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265336"
# }    
#   }
  

  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265338", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265338"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265339", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265339"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265342", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265342"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265343", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265343"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265344", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265344"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265377", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265377"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265378", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265378"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265381", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
#   for(i in 1:length(f)){
#   f[[i]]$RunNumber <- "265381"
# }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265383", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265383"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265385", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265385"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265388", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265388"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265419", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265419"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265420", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265420"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265425", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265425"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265426", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265426"
  # }
  # }
  j <- c(j,f)
}

files <- list.files(path="C:/Users/gerhard/Documents/msc-thesis-data/processed/000265499", pattern="*json", full.names=T, recursive=T)

for(i in 1:length(files)){

  f <- fromJSON(files[i])
  # if(length(f)!=0){
  # for(i in 1:length(f)){
  # f[[i]]$RunNumber <- "265499"
  # }
  # }
  j <- c(j,f)
}

```


```{r,eval=F}
save.image("C:/Users/gerhard/documents/msc-thesis-data/j.rdata")
```

```{r,eval=F}
load("C:/Users/gerhard/documents/msc-thesis-data/j.rdata")
```


```{r,eval=F}

Eta <- sapply(j, `[[`,"Eta")

P <- sapply(j, `[[`,"P")

PT <- sapply(j, `[[`,"PT")

Phi <- sapply(j, `[[`,"Phi")

Theta <- sapply(j, `[[`,"Theta")

col0 <- sapply(j, `[[`,"col0")

col1 <- sapply(j, `[[`,"col1")

col2 <- sapply(j, `[[`,"col2")

col3 <- sapply(j, `[[`,"col3")

col4 <- sapply(j, `[[`,"col4")

col5 <- sapply(j, `[[`,"col5")

dEdX <-  sapply(j, `[[`,"dEdX")

det0 <- sapply(j, `[[`,"det0")

det1 <- sapply(j, `[[`,"det1")

det2 <- sapply(j, `[[`,"det2")

det3 <- sapply(j, `[[`,"det3")

det4 <- sapply(j, `[[`,"det4")

det5 <- sapply(j, `[[`,"det5")

nSigmaElectron <- sapply(j, `[[`,"nSigmaElectron")

nSigmaPion <- sapply(j, `[[`,"nSigmaPion")

pdgCode <- sapply(j, `[[`,"pdgCode")

row0 <- sapply(j, `[[`,"row0")

row1 <- sapply(j, `[[`,"row1")

row2 <- sapply(j, `[[`,"row2")

row3 <- sapply(j, `[[`,"row3")

row4 <- sapply(j, `[[`,"row4")

row5 <- sapply(j, `[[`,"row5")

layer0 <- sapply(j, `[[`,"layer 0")

layer1 <- sapply(j, `[[`,"layer 1")

layer2 <- sapply(j, `[[`,"layer 2")

layer3 <- sapply(j, `[[`,"layer 3")

layer4 <- sapply(j, `[[`,"layer 4")

layer5 <- sapply(j, `[[`,"layer 5")

```


```{r,eval=F}
rm(f,j,files,i)
meta <- data.frame(cbind(col0,col1,col2,col3,col4,col5,det0,det1,det2,det3,det4,det5,
                         row0,row1,row2,row3,row4,row5,dEdX,Eta,nSigmaElectron,
                         nSigmaPion,P,pdgCode,PT,Theta,Phi))

rm(col0,col1,col2,col3,col4,col5,det0,det1,det2,det3,det4,det5,
                         row0,row1,row2,row3,row4,row5,dEdX,Eta,nSigmaElectron,
                         nSigmaPion,P,pdgCode,PT,Theta,Phi)


```



```{r,eval=F}
save(meta,file="C:/Users/gerhard/documents/msc-thesis-data/meta.rdata")
```



```{r}
n0 <- unique(c(which(sapply(layer0,typeof)=="list"),which(sapply(layer0, is.null))))
n1 <- unique(c(which(sapply(layer1,typeof)=="list"),which(sapply(layer1, is.null))))
n2 <- unique(c(which(sapply(layer2,typeof)=="list"),which(sapply(layer2, is.null))))
n3 <- unique(c(which(sapply(layer3,typeof)=="list"),which(sapply(layer3, is.null))))
n4 <- unique(c(which(sapply(layer4,typeof)=="list"),which(sapply(layer4, is.null))))
n5 <- unique(c(which(sapply(layer5,typeof)=="list"),which(sapply(layer5, is.null))))
```

```{r}
meta0 <- meta
meta1 <- meta
meta2 <- meta
meta3 <- meta
meta4 <- meta
meta5 <- meta

rm(meta)

meta0 <- meta0[-n0,]
layer0 <- layer0[-n0]

meta1 <- meta1[-n1,]
layer1 <- layer1[-n1]

meta2 <- meta2[-n2,]
layer2 <- layer2[-n2]

meta3 <- meta3[-n3,]
layer3 <- layer3[-n3]

meta4 <- meta4[-n4,]
layer4 <- layer4[-n4]

meta5 <- meta5[-n5,]
layer5 <- layer5[-n5]

rm(n0,n1,n2,n3,n4,n5)


```



```{r}
meta0$layer <- 0
meta1$layer <- 1
meta2$layer <- 2
meta3$layer <- 3
meta4$layer <- 4
meta5$layer <- 5

meta0$col <- meta0$col0
meta0$det <- meta0$det0
meta0$row <- meta0$row0

meta1$col <- meta1$col1
meta1$det <- meta1$det1
meta1$row <- meta1$row1

meta2$col <- meta2$col2
meta2$det <- meta2$det2
meta2$row <- meta2$row2

meta3$col <- meta3$col3
meta3$det <- meta3$det3
meta3$row <- meta3$row3

meta4$col <- meta4$col4
meta4$det <- meta4$det4
meta4$row <- meta4$row4

meta5$col <- meta5$col5
meta5$det <- meta5$det5
meta5$row <- meta5$row5
```

```{r}
meta0 <- meta0[,-c(1:18)]
meta1 <- meta1[,-c(1:18)]
meta2 <- meta2[,-c(1:18)]
meta3 <- meta3[,-c(1:18)]
meta4 <- meta4[,-c(1:18)]
meta5 <- meta5[,-c(1:18)]
```


```{r}
meta <- data.frame(rbind(meta0,meta1,meta2,meta3,meta4,meta5))

rm(meta1,meta2,meta3,meta4,meta5,meta0)
```


```{r}
names(meta)

aux <- meta[,c(1,3,4,5,7)]

meta <- meta[,-c(1,3,4,5,7)]

names(meta)

y <- ifelse(abs(as.numeric(as.character(meta$pdgCode)))==11,1,0)

meta <- meta[,-2]
```


```{r,eval=F}
save(meta,file="C:/Users/gerhard/documents/msc-thesis-data/meta.rdata")
```

```{r}
save(aux,file="C:/Users/Gerhard/Documents/msc-thesis-data/aux_.rdata")
save(y,file="C:/Users/gerhard/documents/msc-thesis-data/y.rdata")
```

```{r}
require(ggplot2)

P <- data.frame(as.numeric(unlist(aux$P)))

names(P) <- "P"

P$y <- as.factor(y)

ggplot(P,aes(x=P),color=y)+geom_freqpoly()+facet_wrap(~y)
```


```{r}
rm(P)
```



```{r}
h <- hist(as.numeric(aux$P),breaks = c(1,2,3,4,5,6,max(as.numeric(aux$P))))

barplot(h$counts,names.arg=c(h$breaks[1:5],">=6"),col="cornflowerblue")

length(h$breaks)
length(h$counts)
```


```{r}
n <- which(as.numeric(aux$P)>=6)

aux <- aux[-n,]
meta <- meta[-n,]
y <- y[-n]
```

```{r}
require(abind)

fix_dims <- function(x){
  dim(x) <- c(1,dim(x),1)
  return(x)
}

test <- lapply(list(layer0[[1]],layer0[[2]]),fix_dims)



fix_dims <- function(x){
  dim(x) <- c(dim(x)[1],408)
  return(x)
}

layer0 <- lapply(layer0,fix_dims)
layer1 <- lapply(layer1,fix_dims)
layer2 <- lapply(layer2,fix_dims)
layer3 <- lapply(layer3,fix_dims)
layer4 <- lapply(layer4,fix_dims)
layer5 <- lapply(layer5,fix_dims)

test <- do.call(rbind,list(layer0[[1]],layer0[[2]]))

layer0 <- do.call(rbind,layer0)
layer1 <- do.call(rbind,layer1)
layer2 <- do.call(rbind,layer2)
layer3 <- do.call(rbind,layer3)
layer4 <- do.call(rbind,layer4)
layer5 <- do.call(rbind,layer5)

x <- rbind(layer0,layer1,layer2,layer3,layer4,layer5)

rm(layer0,layer1,layer2,layer3,layer4,layer5)
```


```{r}
x <- x[-n,]
```

```{r}
names(meta)

factor_cols <- c(4:7)



test <- sapply(meta[1:2,],unlist)

meta <- sapply(meta, unlist)

meta <- data.frame(meta)

for(i in factor_cols){
  meta[,i] <- as.factor(meta[,i])
}

levels(meta$layer)

```


```{r,eval=F}
save(meta,file="C:/Users/gerhard/documents/msc-thesis-data/meta.rdata")
save(aux,file="C:/Users/Gerhard/Documents/msc-thesis-data/aux_.rdata")
save(y,file="C:/Users/gerhard/documents/msc-thesis-data/y.rdata")
save(x,file="C:/Users/gerhard/documents/msc-thesis-data/x.rdata")
```

```{r}
rm(h,factor_cols,fix_dims,n,i,test)
```

```{r}
rs <- rowSums(x)

n <- which(rs==0)

missing_y <- y[n]

barplot(table(missing_y),names.arg=c("pions","electrons"),col="cornflowerblue")

table(missing_y)

# missing_y
#      0      1 
# 995939 102697 

table(y)

# y
#       0       1 
# 6855599  816942 

#missing:
#        0         1
#0.1452738  0.125709

x <- x[-n,]
meta <- meta[-n,]
aux <- aux[-n,]
y <- y[-n]
```

```{r}
save(meta,file="C:/Users/gerhard/documents/msc-thesis-data/meta.rdata")
save(aux,file="C:/Users/Gerhard/Documents/msc-thesis-data/aux_.rdata")
save(y,file="C:/Users/gerhard/documents/msc-thesis-data/y.rdata")
save(x,file="C:/Users/gerhard/documents/msc-thesis-data/x.rdata")
```

```{r}
rm(list=ls())

load("C:/Users/gerhard/documents/msc-thesis-data/meta.rdata")
load("C:/Users/Gerhard/Documents/msc-thesis-data/aux_.rdata")
load("C:/Users/gerhard/documents/msc-thesis-data/y.rdata")
load("C:/Users/gerhard/documents/msc-thesis-data/x.rdata")

rm(meta,aux)
```


```{r}
require(h2o)

h2o.init(nthreads =-1,min_mem_size="32g",max_mem_size="64g")
```

# Autoencoder for classification

```{r}

x <- data.frame(x)

# rm(meta,aux)
# 
# set.seed(123456)
# 
# train_ind <- sample(1:nrow(x),size=round(0.85*nrow(x)),replace=F)
# 
# x_train <- x[train_ind,]
# x_test <- x[-train_ind,]

x_train.hex <- as.h2o(x=x,destination_frame = "x_train.hex")

AE_model = h2o.deeplearning(
  x = 1:408,
  training_frame = x_train.hex,
  hidden = c(256, 128, 3, 128, 256 ),
  epochs = 600,
  activation = "Tanh",
  autoencoder = TRUE
)

```

```{r}
train_supervised_features2 = h2o.deepfeatures(AE_model, x_train.hex, layer=3)
 
ae_data = as.data.frame(train_supervised_features2)


ae_data$label = as.character(as.vector(y[train_ind]))

library("scatterplot3d")

ae_data$label <- as.factor(ae_data$label)

colors = c("#999999", "#E69F00", "#56B4E9")
shapes = c(16, 17, 18)
shapes <- shapes[as.numeric(ae_data$label)]
colors <- colors[as.numeric(ae_data$label)]

 
s3d <- scatterplot3d(ae_data[,1:3], pch = shapes, color=colors)
legend("bottom", legend = levels(ae_data$label),
      col =  c("#999999", "#E69F00", "#56B4E9"), 
      pch = c(16, 17, 18), 
      inset = -0.25, xpd = TRUE, horiz = TRUE)
```


```{r}
require(ggplot2)
qplot(DF.L3.C1, DF.L3.C2, data = ae_data, color = label, main = "Neural network: 256 - 128 - 3 - 128 - 256 ")
```

#SVM on 3PCAs from VAE

```{r}
svm_dat.hex <- as.h2o(ae_data,"svm_dat.hex")
```

```{r}
sv_model <- h2o.psvm(x=1:3,y=4,training_frame = svm_dat.hex)
```



























